CREATE TABLE [Gusto].[NETDATASOURCEPARAMETER] (
  [NETDATASOURCEPARAMETER_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [STITLE] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](2000) NULL DEFAULT (''),
  [NTUR] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([NETDATASOURCEPARAMETER_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO