CREATE TABLE [Gusto].[OY_TODOFAILED] (
  [OY_TODOFAILED_ROWID] [int] IDENTITY,
  [PPLAN] [int] NULL DEFAULT (0),
  [PEVENT] [int] NULL DEFAULT (0),
  [NSIRA] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([OY_TODOFAILED_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO