CREATE TABLE [Gusto].[EPMYETKIGRUBU] (
  [EPMYETKIGRUBU_ROWID] [int] IDENTITY,
  [ADI] [varchar](30) NULL DEFAULT (''),
  [BSISTEMKULLANICIGRUBU] [smallint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMYETKIGRUBU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO