CREATE TABLE [Gusto].[LED_SOZLESME] (
  [LED_SOZLESME_ROWID] [int] IDENTITY,
  [PMUSAVIR] [int] NOT NULL DEFAULT (0),
  [SSOZLESMECESIDI] [varchar](200) NULL DEFAULT (''),
  [SSOZLESMENO] [varchar](100) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](200) NULL DEFAULT (''),
  [DTSOZLESMEBAS] [smalldatetime] NULL,
  [DTSOZLESMEBIT] [smalldatetime] NULL,
  [DTOLUSTURMA] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([LED_SOZLESME_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO