CREATE TABLE [Gusto].[ONAY_DISABLEITEMS] (
  [PITEM] [int] NULL,
  [PUSAGEDETAY] [int] NULL
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[ONAY_DISABLEITEMS]
  ADD CONSTRAINT [ONAY_DISABLEITEMS_DELETE] FOREIGN KEY ([PUSAGEDETAY]) REFERENCES [Gusto].[ONAY_USAGE_DETAY] ([ONAY_USAGE_DETAY_ROWID]) ON DELETE CASCADE
GO