CREATE TABLE [Gusto].[BPMCG_TCMontajTurleri] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pMontajTuru] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_TCMontajTurleri]
  ADD CONSTRAINT [BPMCG_TCMontajTurleriONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_TCPROFILTURU] ([ROWID]) ON DELETE CASCADE
GO