CREATE TABLE [Gusto].[EPMKilitKart] (
  [EPMKILITKART_ROWID] [int] IDENTITY,
  [PBPMKART] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PSESSION] [int] NULL DEFAULT (0),
  [PKARTTURU] [int] NULL DEFAULT (0),
  [DTTARIH] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([EPMKILITKART_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKilitKart]
  ON [Gusto].[EPMKilitKart] ([PBPMKART], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO