CREATE TABLE [Gusto].[LEAF_SABLON] (
  [LEAF_SABLON_ROWID] [int] IDENTITY,
  [ADI] [varchar](2000) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [FATURATURU] [smallint] NULL DEFAULT (0),
  [BAKTIF] [bit] NULL DEFAULT (0),
  [BGECERLI] [bit] NULL DEFAULT (0),
  [BYENIVERSIYON] [bit] NULL DEFAULT (0),
  [PSTYLESHEET] [int] NULL DEFAULT (0),
  [PDATASOURCE] [int] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [DEGISTIRMETARIHI] [smalldatetime] NULL,
  [DEGISTIRENKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEAF_SABLON_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO