CREATE TABLE [Gusto].[EPMKilit] (
  [EPMKILIT_ROWID] [int] IDENTITY,
  [NKILITTURU] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PSESSION] [int] NULL DEFAULT (0),
  [PBELGETURU] [int] NULL DEFAULT (0),
  [DTTARIH] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([EPMKILIT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKilit]
  ON [Gusto].[EPMKilit] ([NKILITTURU], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO