CREATE TABLE [Gusto].[BPMFT_TALEBETEDARIKCITEKLIFATAMA] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [bTeklifAlinacakMi] [bit] NULL,
  [bAtamaYapildi] [bit] NULL,
  [pTalepSatirlari] [int] NULL DEFAULT (0),
  [pTedarikci] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_TALEBETEDARIKCITEKLIFATAMA]
  ADD CONSTRAINT [BPMFT_TALEBETEDARIKCITEKLIFATAMAONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO