CREATE TABLE [Gusto].[OBJECTMAP] (
  [OBJECTMAP_ROWID] [int] IDENTITY,
  [YEVMIYEHAREKETI_ROWID] [int] NOT NULL DEFAULT (0),
  [EDEFTERSATIRSIRANO] [int] NOT NULL DEFAULT (0),
  [YEVMIYEMADDENO] [int] NOT NULL DEFAULT (0),
  [PLED_BASLIK] [int] NOT NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([OBJECTMAP_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [UX_OBJECTMAP]
  ON [Gusto].[OBJECTMAP] ([PLED_BASLIK])
  INCLUDE ([EDEFTERSATIRSIRANO])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [UX_OBJECTMAP_YEVHAR]
  ON [Gusto].[OBJECTMAP] ([PLED_BASLIK])
  INCLUDE ([YEVMIYEHAREKETI_ROWID], [EDEFTERSATIRSIRANO])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [ux_YevmiyeHareketi_rowid]
  ON [Gusto].[OBJECTMAP] ([YEVMIYEHAREKETI_ROWID], [PLED_BASLIK])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO