CREATE TABLE [Gusto].[OYG_MESAJDURUMLARI] (
  [OYG_MESAJDURUMLARI_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [NFONTCOLOR] [int] NULL DEFAULT (0),
  [NBACKCOLOR] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([OYG_MESAJDURUMLARI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO