CREATE TABLE [GUSTO00005].[MSDigerDetayi] (
  [MSDigerDetayi_rowid] [int] IDENTITY,
  [pMSDigerDetayDevami] [int] NULL DEFAULT (0),
  [pMSDigerKodu] [int] NULL DEFAULT (0),
  [ldDevredenBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenSistemDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenSistemDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [cBakiyeSekli] [char](1) NULL DEFAULT (' '),
  [cBakiyeUyari] [char](1) NULL DEFAULT (' '),
  [cRiskUyari] [char](1) NULL DEFAULT (' '),
  [pKambiyoKari] [int] NULL DEFAULT (0),
  [pKambiyoZarari] [int] NULL DEFAULT (0),
  [pDovizYeriAlacak] [int] NULL DEFAULT (0),
  [pDovizYeriBorc] [int] NULL DEFAULT (0),
  [cDovizTuruAlacak] [char](1) NULL DEFAULT (' '),
  [cDovizTuruBorc] [char](1) NULL DEFAULT (' '),
  [sFaturaUlke] [varchar](50) NULL DEFAULT (''),
  [sFaturaAdresi] [varchar](250) NULL DEFAULT (''),
  [sFaturaPostaKodu] [varchar](10) NULL DEFAULT (''),
  [sFaturaSehir] [varchar](30) NULL DEFAULT (''),
  [sFaturaIlce] [varchar](30) NULL DEFAULT (''),
  [sSevkUlke] [varchar](50) NULL DEFAULT (''),
  [sSevkAdresi] [varchar](250) NULL DEFAULT (''),
  [sSevkPostaKodu] [varchar](10) NULL DEFAULT (''),
  [sSevkSehir] [varchar](30) NULL DEFAULT (''),
  [sSevkIlce] [varchar](30) NULL DEFAULT (''),
  [bFaturaSevkAyni] [bit] NULL DEFAULT (0),
  [pAlanKoduFatura] [int] NULL DEFAULT (0),
  [pAlanKoduSevk] [int] NULL DEFAULT (0),
  [sTelefon1] [varchar](20) NULL DEFAULT (''),
  [sTelefon2] [varchar](20) NULL DEFAULT (''),
  [sTelefon3] [varchar](20) NULL DEFAULT (''),
  [sFaks1] [varchar](20) NULL DEFAULT (''),
  [sFaks2] [varchar](20) NULL DEFAULT (''),
  [sTeleks] [varchar](20) NULL DEFAULT (''),
  [sVergiDairesi] [varchar](30) NULL DEFAULT (''),
  [sVergiNumarasi] [varchar](30) NULL DEFAULT (''),
  [sEmail] [varchar](80) NULL DEFAULT (''),
  [sWebAdresi] [varchar](250) NULL DEFAULT (''),
  [dFaizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [sPeriyodBorc] [char](1) NULL DEFAULT (' '),
  [nPeriyodBorcOzel] [smallint] NULL DEFAULT (0),
  [dFaizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [sPeriyodAlacak] [char](1) NULL DEFAULT (' '),
  [nPeriyodAlacakOzel] [smallint] NULL DEFAULT (0),
  [nFaturaVadeBorc] [smallint] NULL DEFAULT (0),
  [nFaturaVadeAlacak] [smallint] NULL DEFAULT (0),
  [nOpsiyonBorc] [smallint] NULL DEFAULT (0),
  [nOpsiyonAlacak] [smallint] NULL DEFAULT (0),
  [dtMutabakatTarihi] [smalldatetime] NULL,
  [pIskontoTanim] [int] NULL DEFAULT (0),
  [cNakitOdeme] [char](1) NULL DEFAULT (' '),
  [cCekleOdeme] [char](1) NULL DEFAULT (' '),
  [cSenetleOdeme] [char](1) NULL DEFAULT (' '),
  [cNakitTahsilat] [char](1) NULL DEFAULT (' '),
  [cCekleTahsilat] [char](1) NULL DEFAULT (' '),
  [cSenetleTahsilat] [char](1) NULL DEFAULT (' '),
  [nEnUzunAlinanCekVadesi] [smallint] NULL DEFAULT (0),
  [nEnUzunAlacakSenediVadesi] [smallint] NULL DEFAULT (0),
  [nEnUzunVerilenCekVadesi] [smallint] NULL DEFAULT (0),
  [nEnUzunBorcSenediVadesi] [smallint] NULL DEFAULT (0),
  [pBorcDevirHareketi] [int] NULL DEFAULT (0),
  [pAlacakDevirHareketi] [int] NULL DEFAULT (0),
  [dtBorcDevirVadeTarihi] [smalldatetime] NULL,
  [dtAlacakDevirVadeTarihi] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([MSDigerDetayi_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO