CREATE TABLE [Gusto].[EPMFaaliyetGrubu] (
  [EPMFAALIYETGRUBU_ROWID] [int] IDENTITY,
  [SGRUPADI] [varchar](255) NULL DEFAULT (''),
  [SGRUPADIENG] [varchar](255) NULL DEFAULT (''),
  [BKARTGRUBU] [bit] NULL DEFAULT (0),
  [NICONINDEX] [real] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFAALIYETGRUBU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO