CREATE TABLE [Gusto].[EPMKULLANICI] (
  [EPMKULLANICI_ROWID] [int] IDENTITY,
  [ADI] [varchar](255) NULL DEFAULT (''),
  [UZUNADI] [varchar](255) NULL DEFAULT (''),
  [EMAIL] [varchar](255) NULL DEFAULT (''),
  [SKEY] [varchar](255) NULL DEFAULT (''),
  [DTTARIH] [smalldatetime] NULL,
  [BKULLANICIAKTIF] [bit] NULL DEFAULT (0),
  [BBPMGIRIS] [bit] NULL DEFAULT (0),
  [BIZLENEBILIR] [bit] NULL DEFAULT (0),
  [WINDOWSUSERNAME] [varchar](255) NULL DEFAULT (''),
  [PGUSTOKULLANICISI] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKULLANICI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO