CREATE TABLE [Gusto].[EPMItemValue_Memo] (
  [EPMITEMVALUE_MEMO_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [SDEGER] [text] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [SESKIDEGER] [text] NULL,
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_MEMO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_Memo]
  ON [Gusto].[EPMItemValue_Memo] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO