CREATE TABLE [Gusto].[EPMOUTLOOKMAILSUBTASK] (
  [EPMOUTLOOKMAILSUBTASK_ROWID] [int] IDENTITY,
  [POUTLOOKEMAIL] [int] NULL DEFAULT (0),
  [POUTLOOKEMAILRULE] [int] NULL DEFAULT (0),
  [TASKTYPE] [int] NULL DEFAULT (0),
  [PTAMAMLAYANTASK] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMOUTLOOKMAILSUBTASK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMOUTLOOKMAILSUBTASK]
  ON [Gusto].[EPMOUTLOOKMAILSUBTASK] ([POUTLOOKEMAIL], [POUTLOOKEMAILRULE])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO