CREATE TABLE [Gusto].[ONAY_DETAY] (
  [ONAY_DETAY_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL,
  [PPARENT] [int] NULL,
  [PUSERTEMPLATE] [int] NULL,
  [PONAY] [int] NULL,
  [NOPTIONS] [int] NULL,
  PRIMARY KEY CLUSTERED ([ONAY_DETAY_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[ONAY_DETAY]
  ADD CONSTRAINT [ONAY_DETAY_DELETE] FOREIGN KEY ([PONAY]) REFERENCES [Gusto].[ONAYTANIMI] ([ONAYTANIMI_ROWID]) ON DELETE CASCADE
GO