CREATE TABLE [GUSTO00005].[LEI_GELENHAVUZGRUBU] (
  [LEI_GELENHAVUZGRUBU_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_GELENHAVUZGRUBU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO