CREATE TABLE [Gusto].[EPMFaaliyetTuru] (
  [EPMFAALIYETTURU_ROWID] [int] IDENTITY,
  [SKISAADI] [varchar](255) NULL DEFAULT (''),
  [SKISAADIENG] [varchar](255) NULL DEFAULT (''),
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [NDEFAULTDURUM] [smallint] NULL DEFAULT (0),
  [BTEKRARLANABILIR] [bit] NULL DEFAULT (0),
  [BPLANLANABILIR] [bit] NULL DEFAULT (0),
  [STURRENGI] [varchar](255) NULL DEFAULT (''),
  [NCARIBILGISI] [int] NULL DEFAULT (0),
  [BFAALIYETTIMER] [bit] NULL DEFAULT (0),
  [BSUREKLIGIRISKONU] [bit] NULL DEFAULT (0),
  [BAJANGORUNMEZ] [bit] NULL DEFAULT (0),
  [BKONUZORUNLU] [bit] NULL DEFAULT (0),
  [SDURUMLAR] [varchar](255) NULL DEFAULT (''),
  [SGRUPADI1] [varchar](255) NULL DEFAULT (''),
  [SGRUPADI2] [varchar](255) NULL DEFAULT (''),
  [SGRUPADI3] [varchar](255) NULL DEFAULT (''),
  [BGOREVEOTOMATIKRMD] [bit] NULL DEFAULT (0),
  [BGOREVTEKYON] [bit] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMFAALIYETTURU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO