CREATE TABLE [Gusto].[EPMWEBSERVICES] (
  [EPMWEBSERVICES_ROWID] [int] IDENTITY,
  [SADI] [varchar](50) NULL DEFAULT (''),
  [SLINK] [varchar](255) NULL DEFAULT (''),
  [POBJECTCODE] [image] NULL,
  [POBJECTASSM] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMWEBSERVICES_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO