CREATE TABLE [Gusto].[OY_TSablonEmailTo] (
  [OY_TSABLONEMAILTO_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([OY_TSABLONEMAILTO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO