CREATE TABLE [Gusto].[GIZA_KRITERSABLON] (
  [GIZA_KRITERSABLON_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PLISTE] [smallint] NULL DEFAULT (0),
  [SSABLONADI] [varchar](255) NULL DEFAULT (''),
  [BDEFAULT] [bit] NULL DEFAULT (0),
  [OBJLAYOUT] [image] NULL,
  PRIMARY KEY CLUSTERED ([GIZA_KRITERSABLON_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IndGIZA_KRITERSABLON]
  ON [Gusto].[GIZA_KRITERSABLON] ([PKULLANICI], [PLISTE])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO