CREATE TABLE [GUSTO00001].[LEI_EIRSALIYE_YANIT] (
  [LEI_EIRSALIYE_YANIT_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [PIRSALIYE] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NOT NULL DEFAULT (0),
  [NTICARIIRSALIYE] [smallint] NULL DEFAULT (0),
  [EIRSALIYENO] [varchar](255) NOT NULL DEFAULT (''),
  [ETTN] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORID] [varchar](255) NULL DEFAULT (''),
  [NDURUMU] [smallint] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  [BONAYLANDI] [bit] NULL DEFAULT (0),
  [PONAYLAYANKULLANICI] [int] NULL DEFAULT (0),
  [ENTEGRATORDURUMU] [varchar](2000) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_EIRSALIYE_YANIT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEIGELENETTN]
  ON [GUSTO00001].[LEI_EIRSALIYE_YANIT] ([ETTN])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO