CREATE TABLE [Gusto].[FaaliyetLink] (
  [FAALIYETLINK_ROWID] [int] IDENTITY,
  [PKAYNAK] [int] NULL DEFAULT (0),
  [PHEDEF] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([FAALIYETLINK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_FaaliyetLink]
  ON [Gusto].[FaaliyetLink] ([PKAYNAK], [PHEDEF])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO