CREATE TABLE [Gusto].[EPMKilitFaaliyet] (
  [EPMKILITFAALIYET_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PSESSION] [int] NULL DEFAULT (0),
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [DTTARIH] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([EPMKILITFAALIYET_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKilitFaaliyet]
  ON [Gusto].[EPMKilitFaaliyet] ([PFAALIYET], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO