CREATE TABLE [Gusto].[OY_FILEDEFS] (
  [OY_FILEDEFS_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL,
  [SDOSYAADI] [varchar](255) NULL,
  [NCODEPAGE] [int] NULL DEFAULT (0),
  [CSEPERATOR] [varchar](1) NULL DEFAULT (NULL),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([OY_FILEDEFS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO