CREATE TABLE [Gusto].[EPMGorevYetkisi] (
  [EPMGOREVYETKISI_ROWID] [int] IDENTITY,
  [PFAALIYETYETKI] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMGOREVYETKISI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMGorevYetkisi]
  ON [Gusto].[EPMGorevYetkisi] ([PFAALIYETYETKI], [PYETKIGRUBU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO