CREATE TABLE [Gusto].[BPMFT_ATEKLIFIPTAL] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [dtBaslangic] [datetime] NULL,
  [dtBitis] [datetime] NULL,
  [IptalEdilebilirTeklifler] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_ATEKLIFIPTAL]
  ADD CONSTRAINT [BPMFT_ATEKLIFIPTALONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO