CREATE TABLE [Gusto].[LEI_SABLON] (
  [LEI_SABLON_ROWID] [int] IDENTITY,
  [TIP] [smallint] NULL DEFAULT (0),
  [ADI] [varchar](255) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](2000) NULL DEFAULT (''),
  [IRSALIYETURU] [smallint] NULL DEFAULT (0),
  [BAKTIF] [bit] NULL DEFAULT (0),
  [BGECERLI] [bit] NULL DEFAULT (0),
  [PSTYLESHEET] [int] NULL DEFAULT (0),
  [PDATASOURCE] [int] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [DEGISTIRMETARIHI] [smalldatetime] NULL,
  [DEGISTIRENKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  [BYENIVERSIYON] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEI_SABLON_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO