CREATE TABLE [GUSTO00004].[EB_FormulTanimlari] (
  [EB_FormulTanimlari_rowid] [int] IDENTITY,
  [pBeyanname] [int] NULL DEFAULT (0),
  [pSablon] [int] NULL DEFAULT (0),
  [nBeyannameTipi] [int] NULL DEFAULT (0),
  [pFirma] [int] NULL DEFAULT (0),
  [pFormulFirma] [int] NULL DEFAULT (0),
  [nSiraNo] [int] NULL DEFAULT (0),
  [sAnaDegiskenAdi] [varchar](256) NULL DEFAULT (''),
  [sDegiskenAdi] [varchar](256) NULL DEFAULT (''),
  [nDegiskenSatirNo] [int] NULL DEFAULT (0),
  [sHesapKodu] [varchar](256) NULL DEFAULT (''),
  [nBakiyeTipi] [int] NULL DEFAULT (0),
  [ldSabit] [decimal](22, 2) NOT NULL DEFAULT (0),
  [cOperator] [char](1) NULL DEFAULT (' '),
  [cParentezAc] [char](1) NULL DEFAULT (' '),
  [cParentezKapat] [char](1) NULL DEFAULT (' '),
  [nOzelKodTipi] [int] NULL DEFAULT (0),
  [nFisId] [int] NULL DEFAULT (0),
  [sFiltre1] [varchar](250) NULL DEFAULT (''),
  [sFiltre2] [varchar](250) NULL DEFAULT (''),
  [sFiltre3] [varchar](250) NULL DEFAULT (''),
  [sFiltre4] [varchar](250) NULL DEFAULT (''),
  [sFiltre5] [varchar](250) NULL DEFAULT (''),
  [pOlusturanKullanici] [int] NULL DEFAULT (0),
  [dtOlusturma] [smalldatetime] NULL,
  [tmOlusturma] [int] NULL DEFAULT (0),
  [pDegistirenKullanici] [int] NULL DEFAULT (0),
  [dtDegistirme] [smalldatetime] NULL,
  [tmDegistirme] [int] NULL DEFAULT (0),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EB_FormulTanimlari_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO