CREATE TABLE [Gusto].[EPMItemValue_BPMKodu] (
  [EPMITEMVALUE_BPMKODU_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [PKOD] [int] NULL DEFAULT (0),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [PESKIKOD] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_BPMKODU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_BPMKodu]
  ON [Gusto].[EPMItemValue_BPMKodu] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO