CREATE TABLE [Gusto].[BPMFT_ISGUCUCIZELGE] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [SYIL] [varchar](255) NULL DEFAULT (''),
  [BXMLOLUSTURULDU] [bit] NULL,
  [PAY] [int] NULL DEFAULT (-1),
  [PISYERI] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_ISGUCUCIZELGE]
  ADD CONSTRAINT [BPMFT_ISGUCUCIZELGEONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO