CREATE TABLE [GUSTO00005].[StokDetay] (
  [StokDetay_rowid] [int] IDENTITY,
  [pStokKodu] [int] NULL DEFAULT (0),
  [pStokDetayDevami] [int] NULL DEFAULT (0),
  [pStokDetayDevami1] [int] NULL DEFAULT (0),
  [pStokDetayDevami2] [int] NULL DEFAULT (0),
  [ldAsgariSeviye1] [decimal](22, 6) NULL DEFAULT (0),
  [ldAzamiSeviye1] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeSeviyesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldAsgariSeviye2] [decimal](22, 6) NULL DEFAULT (0),
  [ldAzamiSeviye2] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeSeviyesi2] [decimal](22, 6) NULL DEFAULT (0),
  [ldAsgariSeviye3] [decimal](22, 6) NULL DEFAULT (0),
  [ldAzamiSeviye3] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeSeviyesi3] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeMiktari1] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeMiktari2] [decimal](22, 6) NULL DEFAULT (0),
  [ldSiparisEdilmeMiktari3] [decimal](22, 6) NULL DEFAULT (0),
  [ldMinSevkiyatMiktari1] [decimal](22, 6) NULL DEFAULT (0),
  [ldMinSevkiyatMiktari2] [decimal](22, 6) NULL DEFAULT (0),
  [ldMinSevkiyatMiktari3] [decimal](22, 6) NULL DEFAULT (0),
  [ldAlisKDV] [decimal](22, 2) NULL DEFAULT (0),
  [ldSatisKDV] [decimal](22, 2) NULL DEFAULT (0),
  [ldTevkifatOranCarpi] [decimal](22, 2) NULL DEFAULT (0),
  [ldTevkifatOranBolu] [decimal](22, 2) NULL DEFAULT (0),
  [sBirinciBirimAdi] [varchar](10) NULL DEFAULT (''),
  [sIkinciBirimAdi] [varchar](10) NULL DEFAULT (''),
  [cIkinciBirimCarpanBolen] [char](1) NULL DEFAULT (' '),
  [ldIkinciBirimKatsayisi] [decimal](22, 6) NULL DEFAULT (0),
  [sUcuncuBirimAdi] [varchar](10) NULL DEFAULT (''),
  [cUcuncuBirimCarpanBolen] [char](1) NULL DEFAULT (' '),
  [ldUcuncuBirimKatsayisi] [decimal](22, 6) NULL DEFAULT (0),
  [ldBirinciBirim] [decimal](22, 6) NULL DEFAULT (0),
  [ldIkinciBirim] [decimal](22, 6) NULL DEFAULT (0),
  [ldUcuncuBirim] [decimal](22, 6) NULL DEFAULT (0),
  [ldEn1Birim] [real] NULL DEFAULT (0.000000),
  [ldEn2Birim] [real] NULL DEFAULT (0.000000),
  [ldEn3Birim] [real] NULL DEFAULT (0.000000),
  [ldBoy1Birim] [real] NULL DEFAULT (0.000000),
  [ldBoy2Birim] [real] NULL DEFAULT (0.000000),
  [ldBoy3Birim] [real] NULL DEFAULT (0.000000),
  [ldYukseklik1Birim] [real] NULL DEFAULT (0.000000),
  [ldYukseklik2Birim] [real] NULL DEFAULT (0.000000),
  [ldYukseklik3Birim] [real] NULL DEFAULT (0.000000),
  [ldAgirlik1Birim] [real] NULL DEFAULT (0.000000),
  [ldAgirlik2Birim] [real] NULL DEFAULT (0.000000),
  [ldAgirlik3Birim] [real] NULL DEFAULT (0.000000),
  [sOlcuUzunluk1Birim] [varchar](10) NULL DEFAULT (''),
  [sOlcuAgirlik1Birim] [varchar](10) NULL DEFAULT (''),
  [sOlcuUzunluk2Birim] [varchar](10) NULL DEFAULT (''),
  [sOlcuAgirlik2Birim] [varchar](10) NULL DEFAULT (''),
  [sOlcuUzunluk3Birim] [varchar](10) NULL DEFAULT (''),
  [sOlcuAgirlik3Birim] [varchar](10) NULL DEFAULT (''),
  [sBarkod1Birim] [varchar](50) NULL DEFAULT (''),
  [sBarkod2Birim] [varchar](50) NULL DEFAULT (''),
  [sBarkod3Birim] [varchar](50) NULL DEFAULT (''),
  [nVadeSuresiAlis] [smallint] NULL DEFAULT (0),
  [nVadeSuresiSatis] [smallint] NULL DEFAULT (0),
  [cFaturaAltiIskonto] [char](1) NULL DEFAULT (' '),
  [cSatirIskonto] [char](1) NULL DEFAULT (' '),
  [pDovizYeriAlis] [int] NULL DEFAULT (0),
  [cDovizTurAlis] [int] NULL DEFAULT (0),
  [pDovizYeriSatis] [int] NULL DEFAULT (0),
  [cDovizTurSatis] [int] NULL DEFAULT (0),
  [ldTpMalAlimi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpKonsinyeGiren1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpKonsinyeCikaninIadeAlimi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpPerakendeSatisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpToptanSatisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesvikliIthalat1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesviksizIthalat1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDevirGirisi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpImalattanGiris1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpSayimFarkiGirisi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDigerGirisler1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesvikliIhracatIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesviksizIhracatIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDigerCikisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpFasonGiris1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpFasonCikisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpIhracatKayitliMalAlis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpPerakendeSatis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpToptanSatis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpKonsinyeCikis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpKonsinyeGirisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesvikliIhracat1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesviksizIhracat1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpUretimeCikis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpMamulYMHurdaFireCikisi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpHammaddeHurdaFireCikisi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDahiliKullanim1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpSayimFarkiCikisi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDigerCikislar1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpAlimIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesvikliIthalatIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpTesviksizIthalatIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpFasonGirisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpDigerGirisIadesi1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpFasonCikis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldTpIhracatKayitliSatis1] [decimal](22, 6) NULL DEFAULT (0),
  [ldASiparisMiktari] [decimal](22, 6) NULL DEFAULT (0),
  [ldKarsilananASiparisMiktari] [decimal](22, 6) NULL DEFAULT (0),
  [ldVSiparisMiktari] [decimal](22, 6) NULL DEFAULT (0),
  [ldKarsilananVSiparisMiktari] [decimal](22, 6) NULL DEFAULT (0),
  [dtSonKullanim] [smalldatetime] NULL,
  [nRafOmru] [int] NULL DEFAULT (0),
  [dtUretim] [smalldatetime] NULL,
  [ldSabitFireOrani] [decimal](22, 2) NULL DEFAULT (0),
  [ldSatisFireOrani] [decimal](22, 2) NULL DEFAULT (0),
  [bSabitTedarikMi] [bit] NULL DEFAULT (0),
  [dtEnSonMaliyetHesaplamaTarihi] [smalldatetime] NULL,
  [nFireYuvHassasiyet] [tinyint] NULL DEFAULT (0),
  [nEngelleUyarSerbest] [tinyint] NULL DEFAULT (0),
  [nPluNo] [int] NULL DEFAULT (0),
  [nEanTipi] [int] NULL DEFAULT (0),
  [nKisim] [int] NULL DEFAULT (0),
  [bStokHareketIzlemeli] [bit] NULL DEFAULT (0),
  [bSeriLotGirisiZorunlu] [bit] NULL DEFAULT (0),
  [bRezervasyonSistemineDahil] [bit] NULL DEFAULT (1),
  [pTevkifatOranTanimi] [int] NULL DEFAULT (0),
  [nStokBirlestirGunAralik] [smallint] NULL DEFAULT (0),
  [bMRPTalepBirlestirmeYapma] [bit] NULL DEFAULT (0),
  [nMRPKaynaklariKontrolEtme] [smallint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([StokDetay_rowid])
)
ON [PRIMARY]
GO

CREATE INDEX [pStokKodu]
  ON [GUSTO00005].[StokDetay] ([pStokKodu])
  ON [PRIMARY]
GO

CREATE INDEX [sBarkod1Birim]
  ON [GUSTO00005].[StokDetay] ([sBarkod1Birim])
  ON [PRIMARY]
GO

CREATE INDEX [sBarkod2Birim]
  ON [GUSTO00005].[StokDetay] ([sBarkod2Birim])
  ON [PRIMARY]
GO

CREATE INDEX [sBarkod3Birim]
  ON [GUSTO00005].[StokDetay] ([sBarkod3Birim])
  ON [PRIMARY]
GO