CREATE TABLE [Gusto].[EPMPERFLOG] (
  [EPMPERFLOG_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [SHOSTIP] [varchar](255) NULL DEFAULT (''),
  [DTTARIH] [smalldatetime] NULL,
  [NSECONDS] [decimal](22, 6) NULL DEFAULT (0),
  [SLOGTYPE] [varchar](255) NULL DEFAULT (''),
  [SDETAIL] [text] NULL,
  PRIMARY KEY CLUSTERED ([EPMPERFLOG_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_EPMPERFLOG]
  ON [Gusto].[EPMPERFLOG] ([PKULLANICI], [DTTARIH])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO