CREATE TABLE [GUSTO00004].[LEI_EIRSALIYE_ARSIV] (
  [LEI_EIRSALIYE_ARSIV_ROWID] [int] IDENTITY,
  [TIP] [smallint] NOT NULL DEFAULT (0),
  [PIRSALIYE] [int] NOT NULL DEFAULT (0),
  [PEFATURA] [int] NOT NULL DEFAULT (0),
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NOT NULL DEFAULT (0),
  [NTICARIIRSALIYE] [smallint] NULL DEFAULT (0),
  [BIADE] [bit] NULL DEFAULT (0),
  [EIRSALIYENO] [varchar](255) NOT NULL DEFAULT (''),
  [ETTN] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORID] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORDURUMU] [varchar](2000) NULL DEFAULT (''),
  [NDURUMU] [smallint] NULL DEFAULT (0),
  [PZARFID] [int] NOT NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_EIRSALIYE_ARSIV_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_LEIGIDEN]
  ON [GUSTO00004].[LEI_EIRSALIYE_ARSIV] ([PIRSALIYE], [PCARIID])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEIGIDENETTN]
  ON [GUSTO00004].[LEI_EIRSALIYE_ARSIV] ([ETTN])
  ON [PRIMARY]
GO

CREATE INDEX [IND_LEIGIDENNO]
  ON [GUSTO00004].[LEI_EIRSALIYE_ARSIV] ([EIRSALIYENO])
  ON [PRIMARY]
GO