CREATE TABLE [Gusto].[EPMFormItem_Memo] (
  [EPMFORMITEM_MEMO_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SVARSAYILAN] [varchar](2048) NULL DEFAULT (''),
  [NMAXUZUNLUK] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_MEMO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO