CREATE TABLE [Gusto].[EPMFormItem_Date] (
  [EPMFORMITEM_DATE_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [DTVARSAYILAN] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_DATE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO