CREATE TABLE [GUSTO00004].[LEI_SABLON_GELEN] (
  [LEI_SABLON_GELEN_ROWID] [int] IDENTITY,
  [ADI] [varchar](255) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [IRSALIYETURU] [smallint] NULL DEFAULT (0),
  [BAKTIF] [bit] NULL DEFAULT (0),
  [BGECERLI] [bit] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [DEGISTIRMETARIHI] [smalldatetime] NULL,
  [DEGISTIRENKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_SABLON_GELEN_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO