CREATE TABLE [Gusto].[BPMFT_ESERINO] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [nYeniNoFatura] [decimal](22, 6) NULL DEFAULT (0),
  [pEFaturaSeri] [int] NULL DEFAULT (0),
  [nYeniNoArsiv] [decimal](22, 6) NULL DEFAULT (0),
  [pEArsivSeri] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID])
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_ESERINO]
  ADD CONSTRAINT [BPMFT_ESERINOONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO