CREATE TABLE [Gusto].[LEI_DATASOURCE] (
  [LEI_DATASOURCE_ROWID] [int] IDENTITY,
  [ADI] [varchar](255) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [BGECERLI] [bit] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  [BYENIVERSIYON] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEI_DATASOURCE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO