CREATE TABLE [Gusto].[EPMFormItem_ListSel] (
  [EPMFORMITEM_LISTSEL_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SSQL] [varchar](4096) NULL DEFAULT (''),
  [SKEYFIELD] [varchar](255) NULL DEFAULT (''),
  [STEXTFIELD1] [varchar](255) NULL DEFAULT (''),
  [STEXTFIELD2] [varchar](255) NULL DEFAULT (''),
  [NMAXSELECTION] [int] NULL DEFAULT (0),
  [NLINKTOGUSTO] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_LISTSEL_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO