CREATE TABLE [Gusto].[BPMFT_SATINALMATALEPONAY] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [sRedAciklamasi] [varchar](255) NULL DEFAULT (''),
  [pTalepSatiri] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_SATINALMATALEPONAY]
  ADD CONSTRAINT [BPMFT_SATINALMATALEPONAYONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO