CREATE TABLE [Gusto].[EPMRAPOR_CRYSTAL_YETKI] (
  [EPMRAPOR_CRYSTAL_YETKI_ROWID] [int] IDENTITY,
  [PRAPOR] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  [BVIEW] [bit] NULL DEFAULT (0),
  [BPRINT] [bit] NULL DEFAULT (0),
  [BEXPORT] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMRAPOR_CRYSTAL_YETKI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMRAPOR_CRYSTAL_YETKI]
  ON [Gusto].[EPMRAPOR_CRYSTAL_YETKI] ([PRAPOR], [PYETKIGRUBU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO