CREATE TABLE [Gusto].[ONAY_USAGE] (
  [ONAY_USAGE_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL,
  [PONAY] [int] NULL,
  [NFORMTYPE] [int] NULL,
  [NFORMTYPEID] [int] NULL,
  PRIMARY KEY CLUSTERED ([ONAY_USAGE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[ONAY_USAGE]
  ADD CONSTRAINT [ONAY_USAGE_DELETE] FOREIGN KEY ([PONAY]) REFERENCES [Gusto].[ONAYTANIMI] ([ONAYTANIMI_ROWID]) ON DELETE CASCADE
GO