CREATE TABLE [Gusto].[EPMReminder] (
  [EPMREMINDER_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PFAALIYET] [int] NULL DEFAULT (0),
  [DTREMIND] [smalldatetime] NULL,
  [NDURUM] [int] NULL DEFAULT (0),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMREMINDER_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMReminder]
  ON [Gusto].[EPMReminder] ([PKULLANICI], [PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO