CREATE TABLE [Gusto].[BPMKT_BILDIRIM] (
  [ROWID] [int] IDENTITY,
  [PKART] [int] NULL DEFAULT (0),
  [sAciklama] [varchar](2000) NULL DEFAULT (''),
  [dtBildirim] [datetime] NULL,
  [pBildirimSekli] [int] NULL DEFAULT (0),
  [pBildirimTuru] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMKT_BILDIRIM]
  ADD CONSTRAINT [BPMKT_BILDIRIMONDELETE] FOREIGN KEY ([PKART]) REFERENCES [Gusto].[EPMKart] ([EPMKART_ROWID]) ON DELETE CASCADE
GO