CREATE TABLE [Gusto].[EPMItemValue_SubForm] (
  [EPMITEMVALUE_SUBFORM_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [NSIRA] [decimal](22, 2) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_SUBFORM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_SubForm]
  ON [Gusto].[EPMItemValue_SubForm] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO