CREATE TABLE [Gusto].[OY_CSACTIONHISTORY] (
  [OY_CSACTIONHISTORY_ROWID] [int] IDENTITY,
  [PCSACTION] [int] NULL,
  [SCODE] [varchar](max) NULL,
  [PUSER] [int] NULL,
  [DTCHANGE] [datetime] NULL,
  PRIMARY KEY CLUSTERED ([OY_CSACTIONHISTORY_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [Gusto].[OY_CSACTIONHISTORY]
  ADD CONSTRAINT [OY_CSACTIONHISTORYONDEL] FOREIGN KEY ([PCSACTION]) REFERENCES [Gusto].[OY_CSACTIONDEF] ([OY_CSACTIONDEF_ROWID]) ON DELETE CASCADE
GO