CREATE TABLE [Gusto].[EPMDurumlar] (
  [EPMDURUMLAR_ROWID] [int] IDENTITY,
  [SDURUMADI] [varchar](255) NULL DEFAULT (''),
  [SDURUMRENGI] [varchar](15) NULL DEFAULT (''),
  [SDURUMADIENG] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMDURUMLAR_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO