CREATE TABLE [Gusto].[BPMFT_DEPOTRANSFEREMRI] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [dtBasTar] [datetime] NULL,
  [dtBit] [datetime] NULL,
  [DepoTransferEmriIsemirleri] [int] NULL DEFAULT (0),
  [pKullanici] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_DEPOTRANSFEREMRI]
  ADD CONSTRAINT [BPMFT_DEPOTRANSFEREMRIONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO