CREATE TABLE [Gusto].[LED_BASLIK] (
  [LED_BASLIK_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [PDONEM] [int] NULL DEFAULT (0),
  [SAY] [varchar](100) NULL DEFAULT (''),
  [SYIL] [varchar](100) NULL DEFAULT (''),
  [NDURUM] [int] NULL DEFAULT (0),
  [NEDEFTERISLEMDURUM] [int] NULL DEFAULT (0),
  [NIMZAISLEMDURUM] [int] NULL DEFAULT (0),
  [BZAMANDAMGALI] [bit] NULL DEFAULT (0),
  [CERTSERIALNO] [varchar](50) NULL DEFAULT (''),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [ENTEGRATORDURUMU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LED_BASLIK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO