CREATE TABLE [Gusto].[OY_TRIGGERS] (
  [OY_TRIGGERS_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [OWNERTABLE] [varchar](255) NULL DEFAULT (''),
  [CREATEQUERY] [ntext] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([OY_TRIGGERS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO