CREATE TABLE [Gusto].[BPMCG_DegSatirDeptYeni] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pTeklifSatiri] [decimal](22, 6) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_DegSatirDeptYeni]
  ADD CONSTRAINT [BPMCG_DegSatirDeptYeniONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMFT_TEKLIFDEGERLENDIRMEDEPARTMAN] ([ROWID]) ON DELETE CASCADE
GO