CREATE TABLE [GUSTO00001].[VARDIYA_MOLA] (
  [VARDIYA_MOLA_ROWID] [int] IDENTITY,
  [POBJECT] [image] NULL DEFAULT (''),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([VARDIYA_MOLA_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO