CREATE TABLE [GUSTO00003].[NakitAkimYeriDetayi] (
  [NakitAkimYeriDetayi_rowid] [int] IDENTITY,
  [pNakitAkimYeriKodu] [int] NULL DEFAULT (0),
  [pDovizYeriGelir] [int] NULL DEFAULT (0),
  [cKurTuruGelir] [char](1) NULL DEFAULT (' '),
  [pDovizYeriGider] [int] NULL DEFAULT (0),
  [cKurTuruGider] [char](1) NULL DEFAULT (' '),
  [ldAylikGelir1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGelir12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikGider12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGelir12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizGider12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGelir12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizGider12] [decimal](22, 2) NULL DEFAULT (0),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([NakitAkimYeriDetayi_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO