CREATE TABLE [Gusto].[EPMKartTuru] (
  [EPMKARTTURU_ROWID] [int] IDENTITY,
  [SGRUPLAR] [varchar](255) NULL DEFAULT (''),
  [SKISAADI] [varchar](255) NULL DEFAULT (''),
  [SKISAADIENG] [varchar](255) NULL DEFAULT (''),
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [SFORMSIZE] [varchar](255) NULL DEFAULT (''),
  [NICONINDEX] [real] NULL DEFAULT (0),
  [BSERBESTKOD] [bit] NULL DEFAULT (0),
  [BKODUNIQUE] [bit] NULL DEFAULT (0),
  [SKODPREFIX] [varchar](255) NULL DEFAULT (''),
  [NKODDIGITCOUNT] [smallint] NULL DEFAULT (0),
  [NKODSTARTINDEX] [int] NULL DEFAULT (0),
  [BADGORUNSUN] [bit] NULL DEFAULT (0),
  [BADUNIQUE] [bit] NULL DEFAULT (0),
  [BSADECEFORMGIRISI] [bit] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMKARTTURU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO