CREATE TABLE [Gusto].[EPMOUTLOOKMAILTASK] (
  [EPMOUTLOOKMAILTASK_ROWID] [int] IDENTITY,
  [POUTLOOKEMAIL] [int] NULL DEFAULT (0),
  [EMAILID] [varchar](2000) NULL DEFAULT (''),
  [POUTLOOKEMAILRULE] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [BTAMAMLANDI] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMOUTLOOKMAILTASK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMOUTLOOKMAILTASK]
  ON [Gusto].[EPMOUTLOOKMAILTASK] ([POUTLOOKEMAIL], [POUTLOOKEMAILRULE], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO