CREATE TABLE [Gusto].[BPMCG_TCArkalikTurleri] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pArkalik] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_TCArkalikTurleri]
  ADD CONSTRAINT [BPMCG_TCArkalikTurleriONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_TCPROFILTURU] ([ROWID]) ON DELETE CASCADE
GO