CREATE TABLE [Gusto].[TUIK_EVT_ANKET_GONDER] (
  [TUIK_EVT_ANKET_GONDER_ROWID] [int] IDENTITY,
  [PANKET] [int] NULL DEFAULT (0),
  [XML] [image] NULL DEFAULT (''),
  [BYUKLENDI] [bit] NULL DEFAULT (0),
  [WEBSERVISHATAKODU] [int] NULL DEFAULT (0),
  [WEBSERVISHATADETAYI] [varchar](1024) NULL DEFAULT (''),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([TUIK_EVT_ANKET_GONDER_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO