CREATE TABLE [Gusto].[EPMCariBilgiYetki] (
  [EPMCARIBILGIYETKI_ROWID] [int] IDENTITY,
  [PCARIBILGITAB] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [BGRUP] [bit] NULL DEFAULT (0),
  [BGORMEYETKISI] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMCARIBILGIYETKI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMCariBilgiYetki]
  ON [Gusto].[EPMCariBilgiYetki] ([PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO