CREATE TABLE [Gusto].[ONAYCS] (
  [ONAYCS_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL,
  [SVALUE] [varchar](max) NULL,
  [NTYPE] [int] NULL,
  PRIMARY KEY CLUSTERED ([ONAYCS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO