CREATE TABLE [Gusto].[OY_FTPINFOS] (
  [OY_FTPINFOS_ROWID] [int] IDENTITY,
  [SNAME] [varchar](255) NULL DEFAULT (''),
  [BLOCAL] [bit] NULL DEFAULT (0),
  [SPATH] [varchar](255) NULL,
  [SSUBPATH] [varchar](255) NULL,
  [BUSECREDENTIALS] [bit] NULL DEFAULT (0),
  [SUSERNAME] [varchar](255) NULL DEFAULT (''),
  [SPASSWORD] [varchar](255) NULL DEFAULT (''),
  [BUSESSL] [bit] NULL DEFAULT (0),
  [NPORTNUM] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([OY_FTPINFOS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO