CREATE TABLE [Gusto].[EPMKartYetkileri] (
  [EPMKARTYETKILERI_ROWID] [int] IDENTITY,
  [PKARTTURU] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  [BOKUMA] [bit] NULL DEFAULT (0),
  [BEKLEME] [bit] NULL DEFAULT (0),
  [BDEGISTIRME] [bit] NULL DEFAULT (0),
  [BSILME] [bit] NULL DEFAULT (0),
  [BFAALIYETEBAGLAMA] [bit] NULL DEFAULT (0),
  [BTANIMACMA] [bit] NULL DEFAULT (0),
  [BTANIMDEGISTIRME] [bit] NULL DEFAULT (0),
  [BTANIMSILME] [bit] NULL DEFAULT (0),
  [BOLEEKLEME] [bit] NULL DEFAULT (0),
  [BOLESILME] [bit] NULL DEFAULT (0),
  [BOLEACMA] [bit] NULL DEFAULT (0),
  [BKARTYETKISIVERME] [bit] NULL DEFAULT (0),
  [BEXPORT] [bit] NULL DEFAULT (0),
  [BTOPLUISLEM] [bit] NULL DEFAULT (0),
  [BSABLONOLUSTURMA] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKARTYETKILERI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKartYetkileri]
  ON [Gusto].[EPMKartYetkileri] ([PKARTTURU], [PYETKIGRUBU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO