CREATE TABLE [Gusto].[EPMItemValue_Check] (
  [EPMITEMVALUE_CHECK_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [BDEGER] [bit] NULL DEFAULT (0),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [BESKIDEGER] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_CHECK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_Check]
  ON [Gusto].[EPMItemValue_Check] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO