CREATE TABLE [Gusto].[BPMCG_ISGUCUCIZELGE] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [SKIMLIKNO] [varchar](255) NULL DEFAULT (''),
  [PADISOYADI] [int] NULL DEFAULT (0),
  [SSOSYALDURUM] [varchar](255) NULL DEFAULT (''),
  [SISTIHDAMDURUMU] [varchar](255) NULL DEFAULT (''),
  [PMESLEK] [int] NULL DEFAULT (0),
  [DTAYRILMATARIH] [datetime] NULL,
  [SAYRILMADURUM] [varchar](255) NULL DEFAULT (''),
  [SISTENCIKARMA] [varchar](255) NULL DEFAULT (''),
  [NSIRA] [decimal](22, 6) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_ISGUCUCIZELGE]
  ADD CONSTRAINT [BPMCG_ISGUCUCIZELGEONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMFT_ISGUCUCIZELGE] ([ROWID]) ON DELETE CASCADE
GO