CREATE TABLE [Gusto].[EPMFormItem_Web] (
  [EPMFORMITEM_WEB_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SURL] [varchar](50) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_WEB_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO