CREATE TABLE [Gusto].[EPMFormItem_Action] (
  [EPMFORMITEM_ACTION_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_ACTION_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO