CREATE TABLE [GUSTO00005].[LEI_CARIIRSALIYESTYLE] (
  [LEI_CARIIRSALIYESTYLE_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NULL DEFAULT (0),
  [SIRSALIYESERI] [varchar](50) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_CARIIRSALIYESTYLE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEICARISTYLE]
  ON [GUSTO00005].[LEI_CARIIRSALIYESTYLE] ([PSABLON], [PCARIID], [SIRSALIYESERI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO