CREATE TABLE [Gusto].[BPMCG_TCMontajStoklari] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pStokKodu] [int] NULL DEFAULT (0),
  [nAdet] [decimal](22, 6) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_TCMontajStoklari]
  ADD CONSTRAINT [BPMCG_TCMontajStoklariONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_TCMONTAJTURU] ([ROWID]) ON DELETE CASCADE
GO