CREATE TABLE [GUSTO00005].[LEI_EIRSALIYE_IPTAL] (
  [LEI_EIRSALIYE_IPTAL_ROWID] [int] IDENTITY,
  [IPTALACIKLAMASI] [varchar](2000) NULL DEFAULT (''),
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [TIP] [smallint] NOT NULL DEFAULT (0),
  [PIRSALIYE] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NOT NULL DEFAULT (0),
  [NTICARIIRSALIYE] [smallint] NULL DEFAULT (0),
  [BIADE] [bit] NULL DEFAULT (0),
  [EIRSALIYENO] [varchar](255) NOT NULL DEFAULT (''),
  [ETTN] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORDURUMU] [varchar](2000) NULL DEFAULT (''),
  [ENTEGRATORID] [varchar](255) NULL DEFAULT (''),
  [NDURUMU] [smallint] NULL DEFAULT (0),
  [PZARFID] [int] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_EIRSALIYE_IPTAL_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO