CREATE TABLE [Gusto].[EPMOUTLOOKCONTACTLINK] (
  [EPMOUTLOOKCONTACTLINK_ROWID] [int] IDENTITY,
  [NBELGETURU] [int] NULL DEFAULT (0),
  [PBELGEID] [int] NULL DEFAULT (0),
  [OUTLOOKCONTACTID] [varchar](2000) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMOUTLOOKCONTACTLINK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMOUTLOOKCONTACTLINK]
  ON [Gusto].[EPMOUTLOOKCONTACTLINK] ([PBELGEID], [OUTLOOKCONTACTID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO