CREATE TABLE [GUSTO00001].[TUIK_EVT_HARIC_FISLER] (
  [TUIK_EVT_HARIC_FISLER_rowid] [int] IDENTITY,
  [PFIS] [int] NULL DEFAULT (0),
  [PFIRMA] [int] NULL DEFAULT (0),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([TUIK_EVT_HARIC_FISLER_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO