CREATE TABLE [Gusto].[EPMFormItem_BPMKod] (
  [EPMFORMITEM_BPMKOD_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [PBPMKARTTURU] [int] NULL DEFAULT (0),
  [SCONDITION] [varchar](2048) NULL DEFAULT (''),
  [BCOKLUSECIM] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_BPMKOD_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO