CREATE TABLE [Gusto].[CRMLogFaaliyeti] (
  [CRMLOGFAALIYETI_ROWID] [int] IDENTITY,
  [DTSTART] [smalldatetime] NULL,
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [DTEND] [smalldatetime] NULL,
  [KONU] [varchar](255) NULL DEFAULT (''),
  [DURUM] [smallint] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [BTEKRARLANABILIR] [bit] NULL DEFAULT (0),
  [SHOSTIP] [varchar](255) NULL DEFAULT (''),
  [PATAYAN] [varchar](255) NULL DEFAULT (''),
  [SHOSTNAME] [varchar](255) NULL DEFAULT (''),
  [NMODUL] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [RECURRENCEINFO] [varchar](2048) NULL DEFAULT (''),
  [REMINDERINFO] [varchar](2048) NULL DEFAULT (''),
  [PMUSTERI] [int] NULL DEFAULT (0),
  [STIMERVALUE] [varchar](10) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](10) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([CRMLOGFAALIYETI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_CRMLOGFAAL]
  ON [Gusto].[CRMLogFaaliyeti] ([PFAALIYETTURU], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO