CREATE TABLE [GUSTO00004].[PersonelDetayi] (
  [PersonelDetayi_rowid] [int] IDENTITY,
  [pPersonelKodu] [int] NULL DEFAULT (0),
  [sAdres] [varchar](120) NULL DEFAULT (''),
  [sTelefonIs] [varchar](20) NULL DEFAULT (''),
  [pUlke] [int] NULL DEFAULT (0),
  [sUlke] [varchar](30) NULL DEFAULT (''),
  [pSehirIs] [int] NULL DEFAULT (0),
  [sSehirIs] [varchar](30) NULL DEFAULT (''),
  [sTelefonEv] [varchar](20) NULL DEFAULT (''),
  [pSehirEv] [int] NULL DEFAULT (0),
  [sSehirEv] [varchar](30) NULL DEFAULT (''),
  [sTelefonCep] [varchar](20) NULL DEFAULT (''),
  [pSehirCep] [int] NULL DEFAULT (0),
  [sCep] [varchar](30) NULL DEFAULT (''),
  [sEMail] [varchar](120) NULL DEFAULT (''),
  [pMeslegi] [int] NULL DEFAULT (0),
  [nCinsiyeti] [tinyint] NULL DEFAULT (0),
  [sBabaAdi] [varchar](30) NULL DEFAULT (''),
  [sAnaAdi] [varchar](30) NULL DEFAULT (''),
  [sDogumYeri] [varchar](30) NULL DEFAULT (''),
  [dtDogumTarihi] [smalldatetime] NULL,
  [nKanGrubu] [tinyint] NULL DEFAULT (0),
  [nMedeniHali] [tinyint] NULL DEFAULT (0),
  [bUyrugu] [bit] NULL DEFAULT (0),
  [sUyrugu] [varchar](30) NULL DEFAULT (''),
  [sDini] [varchar](20) NULL DEFAULT (''),
  [sIl] [varchar](20) NULL DEFAULT (''),
  [sIlce] [varchar](20) NULL DEFAULT (''),
  [sMahalleKoy] [varchar](30) NULL DEFAULT (''),
  [sCilt_SayfaNo] [varchar](50) NULL DEFAULT (''),
  [sKutukSiraNo] [varchar](15) NULL DEFAULT (''),
  [sSiraNo] [varchar](15) NULL DEFAULT (''),
  [sCuzdanSeriNo] [varchar](15) NULL DEFAULT (''),
  [sCuzdanKayitNo] [varchar](15) NULL DEFAULT (''),
  [sCuzdaninVerildigiYer] [varchar](20) NULL DEFAULT (''),
  [sCuzdaninVerilisNedeni] [varchar](20) NULL DEFAULT (''),
  [dtCuzdanTarihi] [smalldatetime] NULL,
  [nAskerlikDurumu] [tinyint] NULL DEFAULT (0),
  [dtAskerlikTecilTarihi] [smalldatetime] NULL,
  [pIsyeriYasalStatu] [int] NULL DEFAULT (0),
  [pSosyalGuvKurum] [int] NULL DEFAULT (0),
  [sSosyalGuvKurumNo] [varchar](30) NULL DEFAULT (''),
  [nOgrenimDurumu] [tinyint] NULL DEFAULT (0),
  [bGocmenMi] [bit] NULL DEFAULT (0),
  [nOkulOncesiCocuk] [tinyint] NULL DEFAULT (0),
  [nIlkOgretimCocuk] [tinyint] NULL DEFAULT (0),
  [nMeslekSanatCocuk] [tinyint] NULL DEFAULT (0),
  [nLiseCocuk] [tinyint] NULL DEFAULT (0),
  [nYuksekOgretimCocuk] [tinyint] NULL DEFAULT (0),
  [nSakatlikDerecesi] [tinyint] NULL DEFAULT (0),
  [ldDevirBirikenMatrah] [decimal](22, 2) NULL DEFAULT (0),
  [ldDevredenOzelVergiIndirimi] [decimal](22, 2) NULL DEFAULT (0),
  [sEskiIsyeriUnvani] [varchar](50) NULL DEFAULT (''),
  [pEskiIsyeriUlke] [int] NULL DEFAULT (0),
  [pEskiIsyeriSehir] [int] NULL DEFAULT (0),
  [sEskiIsyeriAdresi] [varchar](120) NULL DEFAULT (''),
  [bHukumlu] [bit] NULL DEFAULT (0),
  [sIlkSoyadi] [varchar](50) NULL DEFAULT (''),
  [sVergiKimlikNo] [varchar](50) NULL DEFAULT (''),
  [sMernisNo] [varchar](11) NULL DEFAULT (''),
  [sEmekliSandigiNo] [varchar](30) NULL DEFAULT (''),
  [sBagkurNo] [varchar](30) NULL DEFAULT (''),
  [sDigerSandikAd] [varchar](50) NULL DEFAULT (''),
  [sDigerSandikNo] [varchar](30) NULL DEFAULT (''),
  [dtIseBaslamaTarihi] [smalldatetime] NULL,
  [dtIstenAyrildigiTarih] [smalldatetime] NULL,
  [nIstenAyrilmaNedeni] [tinyint] NULL DEFAULT (0),
  [pCalBakAyrilmaNedeni] [int] NULL DEFAULT (0),
  [pIsKurAyrilmaNedeni] [int] NULL DEFAULT (0),
  [pBankaSubesi] [int] NULL DEFAULT (0),
  [sBankaHesapNo] [varchar](30) NULL DEFAULT (''),
  [sDigitNumarasi] [varchar](10) NULL DEFAULT (''),
  [ldAskerlikBorclanmasi] [decimal](22, 2) NULL DEFAULT (0),
  [dtMemurESKTerfiTarihi] [smalldatetime] NULL,
  [dtMemurKazHakAyTerfiTarihi] [smalldatetime] NULL,
  [pDovizYeriAlacak] [int] NULL DEFAULT (0),
  [cKurTuruAlacak] [char](1) NULL DEFAULT (' '),
  [pDovizYeriBorc] [int] NULL DEFAULT (0),
  [cKurTuruBorc] [char](1) NULL DEFAULT (' '),
  [pYansitmaGGTuru] [int] NULL DEFAULT (0),
  [nTabiOlduguKanun] [tinyint] NULL DEFAULT (1),
  [nKanunTuru] [tinyint] NULL DEFAULT (1),
  [bGorevYonetimi] [bit] NULL DEFAULT (0),
  [sGustoKullanici] [varchar](30) NULL DEFAULT (''),
  [nGorevKontrolSuresi] [int] NULL DEFAULT (0),
  [bGorevUyarisi] [bit] NULL DEFAULT (0),
  [ldAsgariGecimOrani] [decimal](22, 2) NULL DEFAULT (0),
  [nAsgariGecimCocukSayisi] [tinyint] NULL DEFAULT (0),
  [bEsiAsgariIndirimeDahil] [bit] NULL DEFAULT (0),
  [sIBAN] [varchar](30) NULL DEFAULT (''),
  [ldDevredenAGITutari] [decimal](22, 2) NULL DEFAULT (0),
  [pIsKurMeslekKodu] [int] NULL DEFAULT (0),
  [sAdrBulvar] [varchar](30) NULL DEFAULT (''),
  [sAdrCadde] [varchar](30) NULL DEFAULT (''),
  [sAdrSokak] [varchar](30) NULL DEFAULT (''),
  [sAdrMahalleSemt] [varchar](30) NULL DEFAULT (''),
  [sAdrDisKapi] [varchar](30) NULL DEFAULT (''),
  [sAdrIcKapi] [varchar](30) NULL DEFAULT (''),
  [sAdrIlce] [varchar](30) NULL DEFAULT (''),
  [sAdrKoy] [varchar](30) NULL DEFAULT (''),
  [sAdrPostaKod] [varchar](10) NULL DEFAULT (''),
  [nMeslekiYeterlilikDurumu] [tinyint] NULL DEFAULT (0),
  [dtMeslekiYeterlilikBlgTar] [smalldatetime] NULL,
  [dtKanunBaslangicTarihi] [smalldatetime] NULL,
  [dtKanunBitisTarihi] [smalldatetime] NULL,
  [bTurkIsKurumunaKayitDurumu] [bit] NULL DEFAULT (0),
  [b6111denFaydalanmaDurumu] [bit] NULL DEFAULT (0),
  [dtSGKilkGirisTarihi] [smalldatetime] NULL,
  [dtHizmetBitEmeklilikTar] [smalldatetime] NULL,
  [bOtomatikKatilimTabi] [bit] NULL DEFAULT (0),
  [sBESSozlesmeNo] [varchar](30) NULL DEFAULT (''),
  [dtBESGirisTarihi] [smalldatetime] NULL,
  [nIletisimTercihi] [smallint] NULL DEFAULT (0),
  [sBESIBAN] [varchar](30) NULL DEFAULT (''),
  [ldEngellilikOrani] [decimal](22, 2) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([PersonelDetayi_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO