CREATE TABLE [Gusto].[BPMVersion] (
  [BPMVERSION_ROWID] [int] IDENTITY,
  [VERSION] [varchar](50) NULL DEFAULT (''),
  [DTTARIH] [smalldatetime] NULL,
  [PKULLANICI] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([BPMVERSION_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO