CREATE TABLE [Gusto].[BPMFT_RNONAY] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [sRedAciklamasi] [varchar](255) NULL DEFAULT (''),
  [dtTarih] [datetime] NULL,
  [pCRMGorusmeTuru] [int] NULL DEFAULT (0),
  [pKullanici] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_RNONAY]
  ADD CONSTRAINT [BPMFT_RNONAYONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO