CREATE TABLE [GUSTO00003].[LEF_HAVUZGRUBU_YETKI] (
  [LEF_HAVUZGRUBU_YETKI_ROWID] [int] IDENTITY,
  [PHAVUZGRUBU] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEF_HAVUZGRUBU_YETKI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO