CREATE TABLE [Gusto].[OY_GPARAMS] (
  [OY_GPARAMS_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [DTYPE] [int] NULL DEFAULT (0),
  [VALUE] [varchar](255) NULL,
  PRIMARY KEY CLUSTERED ([OY_GPARAMS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO