CREATE TABLE [Gusto].[EPMSEARCHHISTORY] (
  [EPMSEARCHHISTORY_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [SKEY] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMSEARCHHISTORY_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMSEARCHHISTORY]
  ON [Gusto].[EPMSEARCHHISTORY] ([PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO