CREATE TABLE [Gusto].[EPMFormItem_ComboItem] (
  [EPMFORMITEM_COMBOITEM_ROWID] [int] IDENTITY,
  [PCOMBO] [int] NULL DEFAULT (0),
  [SDEGER] [varchar](255) NULL DEFAULT (''),
  [BDEFAULT] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_COMBOITEM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMFormItem_ComboItem]
  ON [Gusto].[EPMFormItem_ComboItem] ([PCOMBO])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO