CREATE TABLE [Gusto].[EPMFaaliyetPaylasim] (
  [EPMFAALIYETPAYLASIM_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFAALIYETPAYLASIM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMFaaliyetPaylasim]
  ON [Gusto].[EPMFaaliyetPaylasim] ([PFAALIYET], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO