CREATE TABLE [Gusto].[EPMFaaliyetBaglanti] (
  [EPMFAALIYETBAGLANTI_ROWID] [int] IDENTITY,
  [SBAGLANTIADI] [varchar](255) NULL DEFAULT (''),
  [BKAYNAKFAALIYET] [bit] NULL DEFAULT (0),
  [PKAYNAKTUR] [int] NULL DEFAULT (0),
  [BHEDEFFAALIYET] [bit] NULL DEFAULT (0),
  [PHEDEFTUR] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFAALIYETBAGLANTI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMFaaliyetBaglanti]
  ON [Gusto].[EPMFaaliyetBaglanti] ([BKAYNAKFAALIYET], [BHEDEFFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO