CREATE TABLE [Gusto].[BPMCG_KALITEVERIGIRISI] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [nYil] [decimal](22, 6) NULL DEFAULT (0),
  [nAy] [int] NULL DEFAULT (0),
  [ldVeri] [decimal](22, 6) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_KALITEVERIGIRISI]
  ADD CONSTRAINT [BPMCG_KALITEVERIGIRISIONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_KALITEMADDELERI] ([ROWID]) ON DELETE CASCADE
GO