CREATE TABLE [Gusto].[OY_IMPORTEDFILES] (
  [OY_IMPORTEDFILES_ROWID] [int] IDENTITY,
  [SNAME] [varchar](255) NULL DEFAULT (''),
  [PEVENT] [int] NULL DEFAULT (0),
  [DTTIME] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([OY_IMPORTEDFILES_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO