CREATE TABLE [GUSTO00001].[LEI_DURUMLOG_GIDEN] (
  [LEI_DURUMLOG_GIDEN_ROWID] [int] IDENTITY,
  [PEIRSALIYE] [int] NULL DEFAULT (0),
  [NESKIDURUM] [smallint] NULL DEFAULT (0),
  [NYENIDURUM] [smallint] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [DTTARIH] [smalldatetime] NULL,
  [BYANIT] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEI_DURUMLOG_GIDEN_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO