CREATE TABLE [GUSTO00001].[DURUSTANIMI] (
  [DURUSTANIMI_ROWID] [int] IDENTITY,
  [DURUS_ADI] [varchar](100) NULL DEFAULT (''),
  [POBJECT] [image] NULL DEFAULT (''),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([DURUSTANIMI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO