CREATE TABLE [Gusto].[EPMItemValue_Combo] (
  [EPMITEMVALUE_COMBO_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [PITEM] [decimal](22, 2) NULL DEFAULT (0),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [PESKIITEM] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_COMBO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_Combo]
  ON [Gusto].[EPMItemValue_Combo] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO