CREATE TABLE [Gusto].[TUIK_EVT_DEGISKEN_TANIM] (
  [TUIK_EVT_DEGISKEN_TANIM_ROWID] [int] IDENTITY,
  [SIRA] [int] NULL DEFAULT (0),
  [ADI] [varchar](255) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](2048) NULL DEFAULT (''),
  [VERI_TIPI] [int] NULL DEFAULT (0),
  [FORM_TANIM] [varchar](512) NULL DEFAULT (''),
  [ETIKET] [varchar](1024) NULL DEFAULT (''),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [FORMULDE_GORUNSUN] [bit] NULL DEFAULT (0),
  [BZORUNLU] [bit] NULL DEFAULT (0),
  [BAKTIF] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([TUIK_EVT_DEGISKEN_TANIM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO