CREATE TABLE [Gusto].[EPMFormItem_SqlText] (
  [EPMFORMITEM_SQLTEXT_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SSQL] [varchar](2048) NULL DEFAULT (''),
  [SNULLDISPLAY] [varchar](255) NULL DEFAULT (''),
  [SFORMAT] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_SQLTEXT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO