CREATE TABLE [GUSTO00004].[AracAylikKilometre] (
  [AracAylikKilometre_rowid] [int] IDENTITY,
  [pAracKodu] [int] NULL DEFAULT (0),
  [nYil] [smallint] NULL DEFAULT (0),
  [ldSayacKmOcak] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmOcak] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmSubat] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmSubat] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmMart] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmMart] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmNisan] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmNisan] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmMayis] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmMayis] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmHaziran] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmHaziran] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmTemmuz] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmTemmuz] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmAgustos] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmAgustos] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmEylul] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmEylul] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmEkim] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmEkim] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmKasim] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmKasim] [decimal](22, 6) NULL DEFAULT (0),
  [ldSayacKmAralik] [decimal](22, 6) NULL DEFAULT (0),
  [ldYapilanKmAralik] [decimal](22, 6) NULL DEFAULT (0),
  [pOlusturanKullanici] [int] NULL DEFAULT (0),
  [dtOlusturma] [smalldatetime] NULL,
  [tmOlusturma] [int] NULL DEFAULT (0),
  [pDegistirenKullanici] [int] NULL DEFAULT (0),
  [dtDegistirme] [smalldatetime] NULL,
  [tmDegistirme] [int] NULL DEFAULT (0),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([AracAylikKilometre_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO