CREATE TABLE [GUSTO00001].[KaliteFaaliyet] (
  [KaliteFaaliyet_rowid] [int] IDENTITY,
  [sSeri] [varchar](60) NULL DEFAULT (''),
  [lNo] [int] NULL DEFAULT (0),
  [dtTarih] [smalldatetime] NULL,
  [cFaaliyetTuru] [char](1) NULL DEFAULT (' '),
  [cFaaliyetDurumu] [char](1) NULL DEFAULT (' '),
  [cBirimTuru] [char](1) NULL DEFAULT (' '),
  [pBirim] [int] NULL DEFAULT (0),
  [dtToplanti] [smalldatetime] NULL,
  [pToplantiHazirlayan] [int] NULL DEFAULT (0),
  [sToplantiZaman] [varchar](255) NULL DEFAULT (''),
  [sToplantiYer] [varchar](255) NULL DEFAULT (''),
  [pIlkTakipSorumlu] [int] NULL DEFAULT (0),
  [bIlkSonuc] [bit] NULL DEFAULT (0),
  [sIlkAciklama] [varchar](255) NULL DEFAULT (''),
  [pIkinciTakipSorumlu] [int] NULL DEFAULT (0),
  [bIkinciSonuc] [bit] NULL DEFAULT (0),
  [sIkinciAciklama] [varchar](255) NULL DEFAULT (''),
  [dtKapatma] [smalldatetime] NULL,
  [pKapatmaSorumlu] [int] NULL DEFAULT (0),
  [pFaaliyetTanimi] [int] NULL DEFAULT (0),
  [sReferansNo] [varchar](20) NULL DEFAULT (''),
  [cOnayDurumu] [char](1) NULL DEFAULT (' '),
  [pOlusturanKullanici] [int] NULL DEFAULT (0),
  [dtOlusturma] [smalldatetime] NULL,
  [tmOlusturma] [int] NULL DEFAULT (0),
  [pDegistirenKullanici] [int] NULL DEFAULT (0),
  [dtDegistirme] [smalldatetime] NULL,
  [tmDegistirme] [int] NULL DEFAULT (0),
  [SubeKodu] [bigint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([KaliteFaaliyet_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO