CREATE TABLE [Gusto].[OY_CSACTIONDEF] (
  [OY_CSACTIONDEF_ROWID] [int] IDENTITY,
  [SNAME] [varchar](255) NULL,
  [SCODE] [varchar](max) NULL,
  [PCREATOR] [int] NULL,
  [DTCREATION] [datetime] NULL,
  [NSTATE] [int] NULL,
  PRIMARY KEY CLUSTERED ([OY_CSACTIONDEF_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO