CREATE TABLE [Gusto].[BPMFT_GIRISKALITE] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [dtBaslangic] [datetime] NULL,
  [dtBitisTarihi] [datetime] NULL,
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_GIRISKALITE]
  ADD CONSTRAINT [BPMFT_GIRISKALITEONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO