CREATE TABLE [Gusto].[OYG_DOSYAEKLERI] (
  [OYG_DOSYAEKLERI_ROWID] [int] IDENTITY,
  [PMESAJ] [int] NULL DEFAULT (0),
  [SFILENAME] [varchar](255) NULL DEFAULT (''),
  [SEXTENSION] [varchar](3) NULL DEFAULT (''),
  [NSIZE] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([OYG_DOSYAEKLERI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO