CREATE TABLE [Gusto].[BPMFT_EDEFTERUPDATE] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [pDonem] [decimal](22, 6) NULL DEFAULT (0),
  [pYevmiyeFisi] [int] NULL DEFAULT (0),
  [sEDefterBelgeSeriNo] [varchar](255) NULL DEFAULT (''),
  [sEDefterAciklama] [varchar](255) NULL DEFAULT (''),
  [nEdefterHareketTuru] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_EDEFTERUPDATE]
  ADD CONSTRAINT [BPMFT_EDEFTERUPDATEONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO