CREATE TABLE [Gusto].[TUIK_EVT_YERELBIRIM] (
  [TUIK_EVT_YERELBIRIM_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [SIRA_NO] [int] NULL DEFAULT (0),
  [BIRIM_NITELIK] [int] NULL DEFAULT (0),
  [CALISAN_SAYI_ORTALAMA] [int] NULL DEFAULT (0),
  [CIRO_BIRIM_PAY] [int] NULL DEFAULT (0),
  [ILKAYIT_NO] [int] NULL DEFAULT (0),
  [KFA_YEREL_ACIKLAMA] [varchar](2048) NULL DEFAULT (''),
  [NACE2_KOD_YEREL] [varchar](10) NULL DEFAULT (''),
  [ODEME_BIRIM_PAY] [int] NULL DEFAULT (0),
  [SGK_SICIL_NO] [varchar](30) NULL DEFAULT (''),
  [VERGIDAIRE_KOD_YEREL] [varchar](5) NULL DEFAULT (''),
  [YATIRIM_BIRIM_PAY] [int] NULL DEFAULT (0),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([TUIK_EVT_YERELBIRIM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO