CREATE TABLE [Gusto].[BPMKT_TEKNIKRESIM] (
  [ROWID] [int] IDENTITY,
  [PKART] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMKT_TEKNIKRESIM]
  ADD CONSTRAINT [BPMKT_TEKNIKRESIMONDELETE] FOREIGN KEY ([PKART]) REFERENCES [Gusto].[EPMKart] ([EPMKART_ROWID]) ON DELETE CASCADE
GO