CREATE TABLE [Gusto].[EPMItemValue_Multi] (
  [EPMITEMVALUE_MULTI_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [PITEM] [decimal](22, 2) NULL DEFAULT (0),
  [SDISPLAY] [varchar](255) NULL DEFAULT (''),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [SESKIDISPLAY] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_MULTI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO