CREATE TABLE [Gusto].[BPMKT_KALITEMADDELERI] (
  [ROWID] [int] IDENTITY,
  [PKART] [int] NULL DEFAULT (0),
  [msSorumlular] [int] NULL DEFAULT (0),
  [sBirimAdi] [varchar](255) NULL,
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMKT_KALITEMADDELERI]
  ADD CONSTRAINT [BPMKT_KALITEMADDELERIONDELETE] FOREIGN KEY ([PKART]) REFERENCES [Gusto].[EPMKart] ([EPMKART_ROWID]) ON DELETE CASCADE
GO