CREATE TABLE [Gusto].[LED_TANIMLAR] (
  [LED_TANIMLAR_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [SKEY] [varchar](250) NULL DEFAULT (''),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LED_TANIMLAR_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO