CREATE TABLE [Gusto].[EPMCUSTOMICON] (
  [EPMCUSTOMICON_ROWID] [int] IDENTITY,
  [ICONOBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMCUSTOMICON_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO