CREATE TABLE [GUSTO00004].[LEF_CARIFATURASTYLE] (
  [LEF_CARIFATURASTYLE_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NULL DEFAULT (0),
  [SFATURASERI] [varchar](50) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEF_CARIFATURASTYLE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEFCARISTYLE]
  ON [GUSTO00004].[LEF_CARIFATURASTYLE] ([PSABLON], [PCARIID], [SFATURASERI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO