CREATE TABLE [GUSTO00005].[LEI_ZARF_GIDEN] (
  [LEI_ZARF_GIDEN_ROWID] [int] IDENTITY,
  [PCARIID] [int] NOT NULL DEFAULT (0),
  [DOSYAADI] [varchar](255) NOT NULL DEFAULT (''),
  [DOSYADIZINI] [varchar](255) NULL DEFAULT (''),
  [NDURUMU] [smallint] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_ZARF_GIDEN_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO