CREATE TABLE [Gusto].[BPMFT_TEKLIFDEGERLENDIRMEDEPARTMAN] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [pTeklifSatirlar] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_TEKLIFDEGERLENDIRMEDEPARTMAN]
  ADD CONSTRAINT [BPMFT_TEKLIFDEGERLENDIRMEDEPARTMANONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO