CREATE TABLE [GUSTO00004].[LEI_IRSALIYENO] (
  [LEI_IRSALIYENO_ROWID] [int] IDENTITY,
  [SKOD] [varchar](3) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [NSONNUMARA] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_IRSALIYENO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO