CREATE TABLE [Gusto].[LEAF_DATASOURCE] (
  [LEAF_DATASOURCE_ROWID] [int] IDENTITY,
  [ADI] [varchar](255) NULL DEFAULT (''),
  [ACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [BGECERLI] [bit] NULL DEFAULT (0),
  [BYENIVERSIYON] [bit] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEAF_DATASOURCE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO