CREATE TABLE [Gusto].[OYG_MESAJALICILARI] (
  [OYG_MESAJALICILARI_ROWID] [int] IDENTITY,
  [POYGMESAJI] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [BOKUNDU] [bit] NULL,
  [BCC] [bit] NULL,
  [NDURUM] [varchar](255) NULL DEFAULT (''),
  [DTREMIND] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([OYG_MESAJALICILARI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO