CREATE TABLE [Gusto].[BPMCG_OzellikKodlari] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pStokKodu] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_OzellikKodlari]
  ADD CONSTRAINT [BPMCG_OzellikKodlariONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_UAOZELLIK] ([ROWID]) ON DELETE CASCADE
GO