CREATE TABLE [Gusto].[OY_XmlOutputs] (
  [OY_XMLOUTPUTS_ROWID] [int] IDENTITY,
  [SPATH] [varchar](255) NULL DEFAULT (''),
  [DTTARIH] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([OY_XMLOUTPUTS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO