CREATE TABLE [Gusto].[EPMFaaliyetCari] (
  [EPMFAALIYETCARI_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PMUSTERIKODU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFAALIYETCARI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMFaaliyetCari]
  ON [Gusto].[EPMFaaliyetCari] ([PFAALIYET], [PMUSTERIKODU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO