CREATE TABLE [Gusto].[EPMONAY_SABLON] (
  [DBTABLENAME_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL,
  [BVARSAYILAN] [bit] NULL,
  [BORTAK] [bit] NULL,
  [PKULLANICI] [int] NULL,
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([DBTABLENAME_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO