CREATE TABLE [Gusto].[BPMFT_TEKLIFDEGERLENDIRMEUY] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [pATS] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_TEKLIFDEGERLENDIRMEUY]
  ADD CONSTRAINT [BPMFT_TEKLIFDEGERLENDIRMEUYONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO