CREATE TABLE [Gusto].[LEI_TANIMLAR] (
  [LEI_TANIMLAR_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [SKEY] [varchar](255) NULL DEFAULT (''),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_TANIMLAR_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO