CREATE TABLE [Gusto].[GIZA_YETKI] (
  [GIZA_YETKI_ROWID] [int] IDENTITY,
  [BKULLANICI] [bit] NULL,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([GIZA_YETKI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IndGizaYetki]
  ON [Gusto].[GIZA_YETKI] ([PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO