CREATE TABLE [Gusto].[BPMFT_ERPTALEPONAYLAMA] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [dtBas] [datetime] NULL,
  [dtBit] [datetime] NULL,
  [OnaylanmamisTalepler] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_ERPTALEPONAYLAMA]
  ADD CONSTRAINT [BPMFT_ERPTALEPONAYLAMAONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO