CREATE TABLE [Gusto].[EPMBaglantiSatiri] (
  [EPMBAGLANTISATIRI_ROWID] [int] IDENTITY,
  [PBAGLANTIBASLIGI] [int] NULL DEFAULT (0),
  [PKAYNAKALAN] [int] NULL DEFAULT (0),
  [PHEDEFALAN] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMBAGLANTISATIRI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO