CREATE TABLE [GUSTO00003].[LEI_CARISABLON_GELEN] (
  [LEI_CARISABLON_GELEN_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NULL DEFAULT (0),
  [SIRSALIYESERI] [varchar](50) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_CARISABLON_GELEN_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEICARISABLONGELEN]
  ON [GUSTO00003].[LEI_CARISABLON_GELEN] ([PSABLON], [PCARIID], [SIRSALIYESERI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO