CREATE TABLE [Gusto].[TUIK_EVT_FORMULLERI] (
  [TUIK_EVT_FORMULLERI_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [SIRANO] [int] NULL DEFAULT (0),
  [DEGISKEN_ADI] [varchar](100) NULL DEFAULT (''),
  [HESAP_KODU] [varchar](100) NULL DEFAULT (''),
  [BAKIYE_TIPI] [int] NULL DEFAULT (0),
  [SABIT] [decimal](22) NULL DEFAULT (0),
  [OPERATOR] [char](1) NULL,
  [PARANTEZAC] [varchar](20) NULL DEFAULT (''),
  [PARANTEZKAPAT] [varchar](20) NULL DEFAULT (''),
  [OZELKOD_TIP] [int] NULL DEFAULT (0),
  [FIS_ID] [int] NULL DEFAULT (0),
  [FILTRE1] [varchar](250) NULL DEFAULT (''),
  [FILTRE2] [varchar](250) NULL DEFAULT (''),
  [FILTRE3] [varchar](250) NULL DEFAULT (''),
  [FILTRE4] [varchar](250) NULL DEFAULT (''),
  [FILTRE5] [varchar](250) NULL DEFAULT (''),
  [SUBE_ID] [int] NULL DEFAULT (0),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PFORMULFIRMA] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([TUIK_EVT_FORMULLERI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO