CREATE TABLE [Gusto].[EPMFaaliyetKullanici] (
  [EPMFAALIYETKULLANICI_ROWID] [int] IDENTITY,
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [NFORMWIDTH] [smallint] NULL DEFAULT (0),
  [NFORMHEIGHT] [smallint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFAALIYETKULLANICI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMFaaliyetKullanici]
  ON [Gusto].[EPMFaaliyetKullanici] ([PFAALIYETTURU], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO