CREATE TABLE [Gusto].[BPMCG_ArkalikOnTanimliStoklar] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pArkalikStok] [int] NULL DEFAULT (0),
  [pOnKorumaStok] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_ArkalikOnTanimliStoklar]
  ADD CONSTRAINT [BPMCG_ArkalikOnTanimliStoklarONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_UAARKONSTOKTANIMLARI] ([ROWID]) ON DELETE CASCADE
GO