CREATE TABLE [Gusto].[EPMSCHCUST] (
  [EPMSCHCUST_ROWID] [int] IDENTITY,
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL,
  [BAKTIF] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMSCHCUST_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO