CREATE TABLE [Gusto].[LED_RAPORKONTROL] (
  [LED_RAPORKONTROL_ROWID] [int] IDENTITY,
  [PLED_BASLIK] [int] NOT NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LED_RAPORKONTROL_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO