CREATE TABLE [Gusto].[TUIK_EVT_HESAP_SONUC] (
  [TUIK_EVT_HESAP_SONUC_ROWID] [int] IDENTITY,
  [DEGISKEN_ADI] [varchar](100) NULL DEFAULT (''),
  [PDONEM] [int] NULL DEFAULT (0),
  [PFORMUL] [int] NULL DEFAULT (0),
  [FORMUL_SONUC] [varchar](500) NULL DEFAULT (''),
  [ANKET_SONUC] [varchar](500) NULL DEFAULT (''),
  [VARSAYILAN_DEGER] [varchar](500) NULL DEFAULT (''),
  [ANKET_FORM_NUMARASI] [int] NULL DEFAULT (0),
  [BDONEM_BILGISI_ICERIYOR] [bit] NULL DEFAULT (0),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [BZORUNLU] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([TUIK_EVT_HESAP_SONUC_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO