CREATE TABLE [Gusto].[BPMFT_VTSATISYONETICISIONAYI] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [sRedAciklama] [varchar](255) NULL DEFAULT (''),
  [OnayBekleyenTeklifler] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_VTSATISYONETICISIONAYI]
  ADD CONSTRAINT [BPMFT_VTSATISYONETICISIONAYIONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO