CREATE TABLE [GUSTO00001].[LEI_HAVUZGRUBU_YETKI] (
  [LEI_HAVUZGRUBU_YETKI_ROWID] [int] IDENTITY,
  [PHAVUZGRUBU] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEI_HAVUZGRUBU_YETKI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO