CREATE TABLE [Gusto].[BPMKT_UAARKONSTOKTANIMLARI] (
  [ROWID] [int] IDENTITY,
  [PKART] [int] NULL DEFAULT (0),
  [pArkalikOnKoruma] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMKT_UAARKONSTOKTANIMLARI]
  ADD CONSTRAINT [BPMKT_UAARKONSTOKTANIMLARIONDELETE] FOREIGN KEY ([PKART]) REFERENCES [Gusto].[EPMKart] ([EPMKART_ROWID]) ON DELETE CASCADE
GO