CREATE TABLE [Gusto].[BPMFT_SAYIMFARKIGIRIS] (
  [ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [sYol] [varchar](255) NULL DEFAULT (''),
  [pDepoKodu] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMFT_SAYIMFARKIGIRIS]
  ADD CONSTRAINT [BPMFT_SAYIMFARKIGIRISONDELETE] FOREIGN KEY ([PFAALIYET]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO