CREATE TABLE [Gusto].[KUL_ONAY_DURUM] (
  [KUL_ONAY_DURUM_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL,
  [SCOLOR] [varchar](6) NULL,
  [NREALVALUE] [int] NULL,
  PRIMARY KEY CLUSTERED ([KUL_ONAY_DURUM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO