CREATE TABLE [GUSTO00005].[LEI_CARIIRSALIYENO] (
  [LEI_CARIIRSALIYENO_ROWID] [int] IDENTITY,
  [PNUMARA] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NULL DEFAULT (0),
  [SIRSALIYESERI] [varchar](50) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEI_CARIIRSALIYENO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO