CREATE TABLE [Gusto].[OYG_MESAJ] (
  [OYG_MESAJ_ROWID] [int] IDENTITY,
  [DTTARIH] [smalldatetime] NULL,
  [STANIMADI] [varchar](255) NULL DEFAULT (''),
  [SGONDEREN] [varchar](255) NULL DEFAULT (''),
  [SKONU] [varchar](255) NULL DEFAULT (''),
  [CONTENT] [image] NULL,
  [PEVENT] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([OYG_MESAJ_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO