CREATE TABLE [Gusto].[CRMOLELink] (
  [CRMOLELINK_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PITEM] [int] NULL DEFAULT (0),
  [SOLENAME] [varchar](255) NULL DEFAULT (''),
  [SOLELINK] [varchar](2048) NULL DEFAULT (''),
  [BMOVEDTOSERVER] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([CRMOLELINK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_CRMOLELink]
  ON [Gusto].[CRMOLELink] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO