CREATE TABLE [GUSTO00003].[LEAF_ARSIV] (
  [LEAF_ARSIV_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL,
  [PFATURA] [int] NOT NULL,
  [PCARIID] [int] NOT NULL,
  [NTICARIFATURA] [int] NULL,
  [BIADE] [int] NULL,
  [EFATURANO] [varchar](255) NOT NULL,
  [ETTN] [varchar](255) NULL,
  [ENTEGRATORID] [varchar](255) NULL,
  [ENTEGRATORDURUMU] [varchar](2000) NULL,
  [NDURUMU] [int] NULL,
  [PZARFID] [int] NULL,
  [OLUSTURMATARIHI] [datetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL,
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([LEAF_ARSIV_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_LEAFGIDEN]
  ON [GUSTO00003].[LEAF_ARSIV] ([PFATURA], [PCARIID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IND_LEAFGIDENETTN]
  ON [GUSTO00003].[LEAF_ARSIV] ([ETTN])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IND_LEAFGIDENNO]
  ON [GUSTO00003].[LEAF_ARSIV] ([EFATURANO])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO