CREATE TABLE [Gusto].[TUIK_EVT_ANKET] (
  [TUIK_EVT_ANKET_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [PDONEM] [int] NULL DEFAULT (0),
  [TUIK_CALISMA_ID] [varchar](500) NULL DEFAULT (''),
  [REFERANSYIL] [int] NULL DEFAULT (0),
  [DTHESAP_BAS_TAR] [smalldatetime] NULL,
  [DTHESAP_BIT_TAR] [smalldatetime] NULL,
  [ANKETADI] [varchar](255) NULL DEFAULT (''),
  [XMLADI] [varchar](255) NULL DEFAULT (''),
  [XMLYOL] [varchar](500) NULL DEFAULT (''),
  [XML] [image] NULL DEFAULT (''),
  [BYUKLENDI] [bit] NULL DEFAULT (0),
  [WEBSERVISHATAKODU] [int] NULL DEFAULT (0),
  [WEBSERVISHATADETAYI] [varchar](2048) NULL DEFAULT (''),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTOLUSTURMA] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  PRIMARY KEY CLUSTERED ([TUIK_EVT_ANKET_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO