CREATE TABLE [Gusto].[EPMRAPOR_CRYSTAL] (
  [EPMRAPOR_CRYSTAL_ROWID] [int] IDENTITY,
  [NTUR] [smallint] NULL DEFAULT (0),
  [PFORMTURU] [int] NULL DEFAULT (0),
  [SRAPORADI] [varchar](255) NULL DEFAULT (''),
  [SDOSYAADI] [varchar](255) NULL DEFAULT (''),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMRAPOR_CRYSTAL_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_EPMRAPOR_CRYSTAL]
  ON [Gusto].[EPMRAPOR_CRYSTAL] ([PFORMTURU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO