CREATE TABLE [Gusto].[EPMItemValue_KodAd] (
  [EPMITEMVALUE_KODAD_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [PKOD] [int] NULL DEFAULT (0),
  [SDISPLAY] [varchar](255) NULL DEFAULT (''),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [SESKIDEGER] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_KODAD_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_KodAd]
  ON [Gusto].[EPMItemValue_KodAd] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO