CREATE TABLE [Gusto].[BPMCG_TCProfiller] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pProfil] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_TCProfiller]
  ADD CONSTRAINT [BPMCG_TCProfillerONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMKT_TCPROFILTURU] ([ROWID]) ON DELETE CASCADE
GO