CREATE TABLE [Gusto].[LED_BERATMAP] (
  [LED_BERATMAP_ROWID] [int] IDENTITY,
  [PFIRMA] [int] NULL DEFAULT (0),
  [PDONEM] [int] NULL DEFAULT (0),
  [NLINENUMBER] [int] NULL DEFAULT (0),
  [BKEBIR] [bit] NULL DEFAULT (0),
  [PLED_BASLIK] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LED_BERATMAP_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO