CREATE TABLE [GUSTO00003].[LEI_EIRSALIYE_GIDEN] (
  [LEI_EIRSALIYE_GIDEN_ROWID] [int] IDENTITY,
  [PSABLON] [int] NOT NULL DEFAULT (0),
  [TIP] [smallint] NULL DEFAULT (0),
  [PIRSALIYE] [int] NOT NULL DEFAULT (0),
  [PCARIID] [int] NOT NULL DEFAULT (0),
  [NTICARIIRSALIYE] [smallint] NULL DEFAULT (0),
  [BIADE] [bit] NULL DEFAULT (0),
  [EIRSALIYENO] [varchar](255) NOT NULL DEFAULT (''),
  [ETTN] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORID] [varchar](255) NULL DEFAULT (''),
  [ENTEGRATORDURUMU] [varchar](2000) NULL DEFAULT (''),
  [NDURUMU] [smallint] NULL DEFAULT (0),
  [PZARFID] [int] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  [BONAYLANDI] [bit] NULL DEFAULT (0),
  [PONAYLAYANKULLANICI] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([LEI_EIRSALIYE_GIDEN_ROWID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_LEIGIDEN]
  ON [GUSTO00003].[LEI_EIRSALIYE_GIDEN] ([PIRSALIYE], [PCARIID], [NDURUMU])
  ON [PRIMARY]
GO

CREATE INDEX [IND_LEIGIDENETTN]
  ON [GUSTO00003].[LEI_EIRSALIYE_GIDEN] ([ETTN])
  ON [PRIMARY]
GO

CREATE UNIQUE INDEX [IND_LEIGIDENNO]
  ON [GUSTO00003].[LEI_EIRSALIYE_GIDEN] ([EIRSALIYENO])
  ON [PRIMARY]
GO

CREATE INDEX [IND_LEIGIDENZARF]
  ON [GUSTO00003].[LEI_EIRSALIYE_GIDEN] ([PZARFID])
  ON [PRIMARY]
GO