CREATE TABLE [Gusto].[EPMCUSTOMLAYOUT] (
  [EPMCUSTOMLAYOUT_ROWID] [int] IDENTITY,
  [NFORMTURU] [int] NULL DEFAULT (0),
  [PFORMTYPEID] [int] NULL DEFAULT (0),
  [POBJECTLAYOUT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMCUSTOMLAYOUT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO