CREATE TABLE [GUSTO00003].[LEAF_FATURANO] (
  [LEAF_FATURANO_ROWID] [int] IDENTITY,
  [SKOD] [varchar](3) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  [NSONNUMARA] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([LEAF_FATURANO_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO