CREATE TABLE [Gusto].[EPMOUTLOOKMAILLINK] (
  [EPMOUTLOOKMAILLINK_ROWID] [int] IDENTITY,
  [NBELGETURU] [int] NULL DEFAULT (0),
  [PBELGEID] [int] NULL DEFAULT (0),
  [POUTLOOKEMAIL] [int] NULL DEFAULT (0),
  [EMAILID] [varchar](2000) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMOUTLOOKMAILLINK_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMOUTLOOKMAILLINK]
  ON [Gusto].[EPMOUTLOOKMAILLINK] ([PBELGEID], [POUTLOOKEMAIL])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO