CREATE TABLE [Gusto].[EPMKartKullanici] (
  [EPMKARTKULLANICI_ROWID] [int] IDENTITY,
  [PKARTTURU] [int] NULL DEFAULT (0),
  [PKULLANICI] [int] NULL DEFAULT (0),
  [NFORMWIDTH] [smallint] NULL DEFAULT (0),
  [NFORMHEIGHT] [smallint] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKARTKULLANICI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKartKullanici]
  ON [Gusto].[EPMKartKullanici] ([PKARTTURU], [PKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO