CREATE TABLE [Gusto].[EPMYetkiler] (
  [EPMYETKILER_ROWID] [int] IDENTITY,
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  [BKULLANMA] [bit] NULL DEFAULT (0),
  [BGOREVATAMA] [bit] NULL DEFAULT (0),
  [BFAALIYETBAGLAMA] [bit] NULL DEFAULT (0),
  [BFAALIYETEBAGLAMA] [bit] NULL DEFAULT (0),
  [BBAGLIFAALIYETSILME] [bit] NULL DEFAULT (0),
  [BTANIMACMA] [bit] NULL DEFAULT (0),
  [BTANIMDEGISTIRME] [bit] NULL DEFAULT (0),
  [BTANIMSILME] [bit] NULL DEFAULT (0),
  [BOLEEKLEME] [bit] NULL DEFAULT (0),
  [BOLESILME] [bit] NULL DEFAULT (0),
  [BOLEACMA] [bit] NULL DEFAULT (0),
  [BKONUDEGISTIRME] [bit] NULL DEFAULT (0),
  [BKARTDEGISTIRME] [bit] NULL DEFAULT (0),
  [BEXPORT] [bit] NULL DEFAULT (0),
  [NGECMISFAALIYETSILME] [smallint] NULL DEFAULT (0),
  [NGECMISFAALIYETDEGISTIRME] [int] NULL DEFAULT (0),
  [BSABLONOLUSTURMA] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMYETKILER_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMYetkiler]
  ON [Gusto].[EPMYetkiler] ([PFAALIYETTURU], [PYETKIGRUBU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO