CREATE TABLE [Gusto].[EPMKULLANICIYETKIGRUBU] (
  [EPMKULLANICIYETKIGRUBU_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKULLANICIYETKIGRUBU_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKULLANICIYETKIGRUBU]
  ON [Gusto].[EPMKULLANICIYETKIGRUBU] ([PKULLANICI], [PYETKIGRUBU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO