CREATE TABLE [Gusto].[EPMGorevReminder] (
  [EPMGOREVREMINDER_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [PATAYANFAALIYET] [int] NULL DEFAULT (0),
  [PFAALIYET] [int] NULL DEFAULT (0),
  [DTREMIND] [smalldatetime] NULL,
  [PAKTIFKULLANICI] [int] NULL DEFAULT (0),
  [SACIKLAMA] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMGOREVREMINDER_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMGorevReminder]
  ON [Gusto].[EPMGorevReminder] ([PKULLANICI], [PATAYANFAALIYET], [PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO