CREATE TABLE [Gusto].[EPMFormItem_Text] (
  [EPMFORMITEM_TEXT_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SVARSAYILAN] [varchar](255) NULL DEFAULT (''),
  [NMAXUZUNLUK] [int] NULL DEFAULT (0),
  [NLOOKUPTYPE] [real] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_TEXT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO