CREATE TABLE [Gusto].[EPMFormItem_List] (
  [EPMFORMITEM_LIST_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SSQL] [varchar](4096) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMFORMITEM_LIST_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO