CREATE TABLE [GUSTO00003].[HesapToplam] (
  [HesapToplam_rowid] [int] IDENTITY,
  [pHesapKodu] [int] NOT NULL DEFAULT (0),
  [pDonem] [int] NOT NULL DEFAULT (0),
  [ldAcilisBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldAcilisAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldAcilisDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldAcilisDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldAcilisSistemDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldAcilisSistemDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikDovizAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizBorc12] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak1] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak2] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak3] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak4] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak5] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak6] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak7] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak8] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak9] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak10] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak11] [decimal](22, 2) NULL DEFAULT (0),
  [ldAylikSistemDovizAlacak12] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisSistemDovizBorc] [decimal](22, 2) NULL DEFAULT (0),
  [ldKapanisSistemDovizAlacak] [decimal](22, 2) NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([HesapToplam_rowid]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX [HesapDonemKey]
  ON [GUSTO00003].[HesapToplam] ([pHesapKodu], [pDonem])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO