CREATE TABLE [Gusto].[EPMONAYFAALIYET] (
  [EPMONAYFAALIYET_ROWID] [int] IDENTITY,
  [PFORM] [int] NULL,
  [PNODEUSAGE] [int] NULL,
  [SACIKLAMA] [varchar](1000) NULL,
  [PSTATUS] [int] NULL,
  [POLUSTURAN] [int] NULL,
  [DTOLUSTURMA] [datetime] NULL,
  [PDEGISTIREN] [int] NULL,
  [DTDEGISTIRME] [datetime] NULL,
  PRIMARY KEY CLUSTERED ([EPMONAYFAALIYET_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[EPMONAYFAALIYET]
  ADD CONSTRAINT [EPMONAYFAALIYET_DELETE] FOREIGN KEY ([PFORM]) REFERENCES [Gusto].[EPMFaaliyet] ([EPMFAALIYET_ROWID]) ON DELETE CASCADE
GO

ALTER TABLE [Gusto].[EPMONAYFAALIYET]
  ADD CONSTRAINT [EPMONAYFAALIYET_DELETEUS] FOREIGN KEY ([PNODEUSAGE]) REFERENCES [Gusto].[ONAY_USAGE_DETAY] ([ONAY_USAGE_DETAY_ROWID]) ON DELETE CASCADE
GO