CREATE TABLE [Gusto].[OY_TAction_Email] (
  [OY_TACTION_EMAIL_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [PEVENT] [int] NULL DEFAULT (0),
  [NEVENTTYPE] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([OY_TACTION_EMAIL_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO