CREATE TABLE [Gusto].[EPMTanimlar] (
  [EPMTANIMLAR_ROWID] [int] IDENTITY,
  [PKULLANICI] [int] NULL DEFAULT (0),
  [NKEYID] [int] NULL DEFAULT (0),
  [SKEY] [varchar](255) NULL DEFAULT (''),
  [SVALUE] [varchar](2048) NULL DEFAULT (''),
  [NVALUE] [int] NULL DEFAULT (0),
  [DTVALUE] [smalldatetime] NULL,
  [POBJECT] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMTANIMLAR_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE INDEX [IND_EPMTanimlar]
  ON [Gusto].[EPMTanimlar] ([PKULLANICI], [NKEYID])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO