CREATE TABLE [Gusto].[ONAY_MAPPEDCONTROLS] (
  [PITEM] [int] NULL,
  [SLABEL] [varchar](255) NULL,
  [PUSAGEDETAY] [int] NULL
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[ONAY_MAPPEDCONTROLS]
  ADD CONSTRAINT [ONAY_MAPPEDCONTROLS_DELETE] FOREIGN KEY ([PUSAGEDETAY]) REFERENCES [Gusto].[ONAY_USAGE_DETAY] ([ONAY_USAGE_DETAY_ROWID]) ON DELETE CASCADE
GO