CREATE TABLE [Gusto].[ONAYCSUSAGE] (
  [ONAYCSUSAGE_ROWID] [int] IDENTITY,
  [PCS] [int] NULL,
  [PUSAGENODE] [int] NULL,
  [BACTIVE] [bit] NULL,
  PRIMARY KEY CLUSTERED ([ONAYCSUSAGE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[ONAYCSUSAGE]
  ADD CONSTRAINT [ONAYCSUSAGE_DELETE] FOREIGN KEY ([PUSAGENODE]) REFERENCES [Gusto].[ONAY_USAGE_DETAY] ([ONAY_USAGE_DETAY_ROWID]) ON DELETE CASCADE
GO

ALTER TABLE [Gusto].[ONAYCSUSAGE]
  ADD CONSTRAINT [ONAYCSUSAGE_DELETECS] FOREIGN KEY ([PCS]) REFERENCES [Gusto].[ONAYCS] ([ONAYCS_ROWID]) ON DELETE CASCADE
GO