CREATE TABLE [Gusto].[EPMCariSecimi] (
  [EPMCARISECIMI_ROWID] [int] IDENTITY,
  [PFAALIYETTURU] [int] NULL DEFAULT (0),
  [BZORUNLU] [bit] NULL DEFAULT (0),
  [BCOKLUSECIM] [bit] NULL DEFAULT (0),
  [SCONDITION] [varchar](2048) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMCARISECIMI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMCariSecimi]
  ON [Gusto].[EPMCariSecimi] ([PFAALIYETTURU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO