CREATE TABLE [Gusto].[EPMGrupBaglanti] (
  [EPMGRUPBAGLANTI_ROWID] [int] IDENTITY,
  [PGRUP] [varchar](255) NULL DEFAULT (''),
  [BFAALIYET] [bit] NULL DEFAULT (0),
  [PGRUPITEM] [real] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMGRUPBAGLANTI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO