CREATE TABLE [Gusto].[BPMCG_Malzemeler] (
  [ROWID] [int] IDENTITY,
  [PPARENT] [int] NULL DEFAULT (0),
  [pStokKodu] [int] NULL DEFAULT (0),
  [ldMiktar] [decimal](22, 6) NULL DEFAULT (0),
  [sBirim] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMCG_Malzemeler]
  ADD CONSTRAINT [BPMCG_MalzemelerONDELETE] FOREIGN KEY ([PPARENT]) REFERENCES [Gusto].[BPMFT_ISEMRITEKNIKRESIM] ([ROWID]) ON DELETE CASCADE
GO