CREATE TABLE [Gusto].[EPMKart] (
  [EPMKART_ROWID] [int] IDENTITY,
  [PKARTTURU] [int] NULL DEFAULT (0),
  [SKODU] [varchar](255) NULL DEFAULT (''),
  [SADI] [varchar](255) NULL DEFAULT (''),
  [PSONFAALIYET] [int] NULL DEFAULT (0),
  [POLUSTURAN] [int] NULL DEFAULT (0),
  [DTOLUSMA] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTDEGISME] [smalldatetime] NULL,
  [SUBEKODU] [bigint] NULL,
  [PFIRMA] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKART_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKart1]
  ON [Gusto].[EPMKart] ([SKODU])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKart2]
  ON [Gusto].[EPMKart] ([SKODU], [SADI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKart3]
  ON [Gusto].[EPMKart] ([PSONFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO