CREATE TABLE [Gusto].[EPMItemValue_Text] (
  [EPMITEMVALUE_TEXT_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [SDEGER] [varchar](255) NULL DEFAULT (''),
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [SESKIDEGER] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_TEXT_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO