CREATE TABLE [Gusto].[OY_EventPlan] (
  [OY_EVENTPLAN_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [SGRUP] [varchar](255) NULL DEFAULT (''),
  [BACTIVE] [bit] NULL DEFAULT (1),
  [PCONDITION] [int] NULL DEFAULT (0),
  [PSCHEDULE] [int] NULL DEFAULT (0),
  [PSERVERID] [int] NULL DEFAULT (0),
  [HTYPE] [int] NULL DEFAULT (0),
  [SACIKLAMA] [varchar](255) NULL,
  PRIMARY KEY CLUSTERED ([OY_EVENTPLAN_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO