CREATE TABLE [Gusto].[EPMGPARAMS] (
  [EPMGPARAMS_ROWID] [int] IDENTITY,
  [SADI] [varchar](50) NULL DEFAULT (''),
  [NTYPE] [int] NULL DEFAULT (0),
  [VALUE] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMGPARAMS_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO