CREATE TABLE [Gusto].[BPMKT_DEPARTMAN] (
  [ROWID] [int] IDENTITY,
  [PKART] [int] NULL DEFAULT (0),
  [sAciklama] [varchar](255) NULL DEFAULT (''),
  [pDepBagliKullanicilar] [int] NULL DEFAULT (0),
  [pStokGruplari] [int] NULL DEFAULT (0),
  [pDepYoneticisi] [int] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

ALTER TABLE [Gusto].[BPMKT_DEPARTMAN]
  ADD CONSTRAINT [BPMKT_DEPARTMANONDELETE] FOREIGN KEY ([PKART]) REFERENCES [Gusto].[EPMKart] ([EPMKART_ROWID]) ON DELETE CASCADE
GO