CREATE TABLE [Gusto].[EPMItemValue_Date] (
  [EPMITEMVALUE_DATE_ROWID] [int] IDENTITY,
  [PFAALIYET] [int] NULL DEFAULT (0),
  [PEKBILGITURU] [int] NULL DEFAULT (0),
  [DTDEGER] [smalldatetime] NULL,
  [DTDEGISTIRME] [smalldatetime] NULL,
  [PDEGISTIREN] [int] NULL DEFAULT (0),
  [DTESKIDEGER] [varchar](255) NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([EPMITEMVALUE_DATE_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMItemValue_Date]
  ON [Gusto].[EPMItemValue_Date] ([PFAALIYET])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO