CREATE TABLE [Gusto].[GIZA_YETKI_TANIM] (
  [GIZA_YETKI_TANIM_ROWID] [int] IDENTITY,
  [PKULGUR] [int] NULL DEFAULT (0),
  [BYETKI] [bit] NULL,
  PRIMARY KEY CLUSTERED ([GIZA_YETKI_TANIM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IndGizaYetkiTanim]
  ON [Gusto].[GIZA_YETKI_TANIM] ([PKULGUR])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO