CREATE TABLE [Gusto].[EPMACTIONASSM] (
  [EPMACTIONASSM_ROWID] [int] IDENTITY,
  [NFORMTURU] [int] NULL DEFAULT (0),
  [BREQUIREUPDATE] [bit] NULL DEFAULT (0),
  [PFORMTYPEID] [int] NULL DEFAULT (0),
  [POBJECTCODE] [image] NULL,
  [POBJECTASSM] [image] NULL,
  PRIMARY KEY CLUSTERED ([EPMACTIONASSM_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO