CREATE TABLE [Gusto].[PERSPEKTIFDASHBOARD] (
  [PERSPEKTIFDASHBOARD_ROWID] [int] IDENTITY,
  [SADI] [varchar](255) NULL DEFAULT (''),
  [STITLE] [varchar](255) NULL DEFAULT (''),
  [SACIKLAMA] [varchar](2000) NULL DEFAULT (''),
  [NPLATFORM] [int] NULL DEFAULT (0),
  [BSTND] [bit] NULL DEFAULT (0),
  [OLUSTURMATARIHI] [smalldatetime] NULL,
  [OLUSTURANKULLANICI] [int] NULL DEFAULT (0),
  [DEGISTIRMETARIHI] [smalldatetime] NULL,
  [DEGISTIRENKULLANICI] [int] NULL DEFAULT (0),
  [POBJECT] [image] NULL DEFAULT (''),
  PRIMARY KEY CLUSTERED ([PERSPEKTIFDASHBOARD_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO