CREATE TABLE [Gusto].[EPMKartGormeYetkisi] (
  [EPMKARTGORMEYETKISI_ROWID] [int] IDENTITY,
  [PKARTTURU] [int] NULL DEFAULT (0),
  [PYETKIGRUBU] [varchar](255) NULL DEFAULT (''),
  [PDIGERKULLANICI] [int] NULL DEFAULT (0),
  [BOKUMA] [bit] NULL DEFAULT (0),
  [BDEGISTIRME] [bit] NULL DEFAULT (0),
  [BSILME] [bit] NULL DEFAULT (0),
  PRIMARY KEY CLUSTERED ([EPMKARTGORMEYETKISI_ROWID]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO

CREATE INDEX [IND_EPMKartGormeYetkisi]
  ON [Gusto].[EPMKartGormeYetkisi] ([PKARTTURU], [PYETKIGRUBU], [PDIGERKULLANICI])
  WITH (FILLFACTOR = 90)
  ON [PRIMARY]
GO